names =  {
    "ABILITY_NONE": "None",
    "ABILITY_STENCH": "Stench",
    "ABILITY_DRIZZLE": "Drizzle",
    "ABILITY_SPEED_BOOST": "Speed Boost",
    "ABILITY_BATTLE_ARMOR": "Battle Armor",
    "ABILITY_STURDY": "Sturdy",
    "ABILITY_DAMP": "Damp",
    "ABILITY_LIMBER": "Limber",
    "ABILITY_SAND_VEIL": "Sand Veil",
    "ABILITY_STATIC": "Static",
    "ABILITY_VOLT_ABSORB": "Volt Absorb",
    "ABILITY_WATER_ABSORB": "Water Absorb",
    "ABILITY_OBLIVIOUS": "Oblivious",
    "ABILITY_CLOUD_NINE": "Cloud Nine",
    "ABILITY_COMPOUND_EYES": "Compound Eyes",
    "ABILITY_INSOMNIA": "Insomnia",
    "ABILITY_COLOR_CHANGE": "Color Change",
    "ABILITY_IMMUNITY": "Immunity",
    "ABILITY_FLASH_FIRE": "Flash Fire",
    "ABILITY_SHIELD_DUST": "Shield Dust",
    "ABILITY_OWN_TEMPO": "Own Tempo",
    "ABILITY_SUCTION_CUPS": "Suction Cups",
    "ABILITY_INTIMIDATE": "Intimidate",
    "ABILITY_SHADOW_TAG": "Shadow Tag",
    "ABILITY_ROUGH_SKIN": "Rough Skin",
    "ABILITY_WONDER_GUARD": "Wonder Guard",
    "ABILITY_LEVITATE": "Levitate",
    "ABILITY_EFFECT_SPORE": "Effect Spore",
    "ABILITY_SYNCHRONIZE": "Synchronize",
    "ABILITY_CLEAR_BODY": "Clear Body",
    "ABILITY_NATURAL_CURE": "Natural Cure",
    "ABILITY_LIGHTNING_ROD": "Lightning Rod",
    "ABILITY_SERENE_GRACE": "Serene Grace",
    "ABILITY_SWIFT_SWIM": "Swift Swim",
    "ABILITY_CHLOROPHYLL": "Chlorophyll",
    "ABILITY_ILLUMINATE": "Illuminate",
    "ABILITY_TRACE": "Trace",
    "ABILITY_HUGE_POWER": "Huge Power",
    "ABILITY_POISON_POINT": "Poison Point",
    "ABILITY_INNER_FOCUS": "Inner Focus",
    "ABILITY_MAGMA_ARMOR": "Magma Armor",
    "ABILITY_WATER_VEIL": "Water Veil",
    "ABILITY_MAGNET_PULL": "Magnet Pull",
    "ABILITY_SOUNDPROOF": "Soundproof",
    "ABILITY_RAIN_DISH": "Rain Dish",
    "ABILITY_SAND_STREAM": "Sand Stream",
    "ABILITY_PRESSURE": "Pressure",
    "ABILITY_THICK_FAT": "Thick Fat",
    "ABILITY_EARLY_BIRD": "Early Bird",
    "ABILITY_FLAME_BODY": "Flame Body",
    "ABILITY_RUN_AWAY": "Run Away",
    "ABILITY_KEEN_EYE": "Keen Eye",
    "ABILITY_HYPER_CUTTER": "Hyper Cutter",
    "ABILITY_PICKUP": "Pickup",
    "ABILITY_TRUANT": "Truant",
    "ABILITY_HUSTLE": "Hustle",
    "ABILITY_CUTE_CHARM": "Cute Charm",
    "ABILITY_PLUS": "Plus",
    "ABILITY_MINUS": "Minus",
    "ABILITY_FORECAST": "Forecast",
    "ABILITY_STICKY_HOLD": "Sticky Hold",
    "ABILITY_SHED_SKIN": "Shed Skin",
    "ABILITY_GUTS": "Guts",
    "ABILITY_MARVEL_SCALE": "Marvel Scale",
    "ABILITY_LIQUID_OOZE": "Liquid Ooze",
    "ABILITY_OVERGROW": "Overgrow",
    "ABILITY_BLAZE": "Blaze",
    "ABILITY_TORRENT": "Torrent",
    "ABILITY_SWARM": "Swarm",
    "ABILITY_ROCK_HEAD": "Rock Head",
    "ABILITY_DROUGHT": "Drought",
    "ABILITY_ARENA_TRAP": "Arena Trap",
    "ABILITY_VITAL_SPIRIT": "Vital Spirit",
    "ABILITY_WHITE_SMOKE": "White Smoke",
    "ABILITY_PURE_POWER": "Pure Power",
    "ABILITY_SHELL_ARMOR": "Shell Armor",
    "ABILITY_AIR_LOCK": "Air Lock",
    "ABILITY_TANGLED_FEET": "Tangled Feet",
    "ABILITY_MOTOR_DRIVE": "Motor Drive",
    "ABILITY_RIVALRY": "Rivalry",
    "ABILITY_STEADFAST": "Steadfast",
    "ABILITY_SNOW_CLOAK": "Snow Cloak",
    "ABILITY_GLUTTONY": "Gluttony",
    "ABILITY_ANGER_POINT": "Anger Point",
    "ABILITY_UNBURDEN": "Unburden",
    "ABILITY_HEATPROOF": "Heatproof",
    "ABILITY_SIMPLE": "Simple",
    "ABILITY_DRY_SKIN": "Dry Skin",
    "ABILITY_DOWNLOAD": "Download",
    "ABILITY_IRON_FIST": "Iron Fist",
    "ABILITY_POISON_HEAL": "Poison Heal",
    "ABILITY_ADAPTABILITY": "Adaptability",
    "ABILITY_SKILL_LINK": "Skill Link",
    "ABILITY_HYDRATION": "Hydration",
    "ABILITY_SOLAR_POWER": "Solar Power",
    "ABILITY_QUICK_FEET": "Quick Feet",
    "ABILITY_NORMALIZE": "Normalize",
    "ABILITY_SNIPER": "Sniper",
    "ABILITY_MAGIC_GUARD": "Magic Guard",
    "ABILITY_NO_GUARD": "No Guard",
    "ABILITY_STALL": "Stall",
    "ABILITY_TECHNICIAN": "Technician",
    "ABILITY_LEAF_GUARD": "Leaf Guard",
    "ABILITY_KLUTZ": "Klutz",
    "ABILITY_MOLD_BREAKER": "Mold Breaker",
    "ABILITY_SUPER_LUCK": "Super Luck",
    "ABILITY_AFTERMATH": "Aftermath",
    "ABILITY_ANTICIPATION": "Anticipation",
    "ABILITY_FOREWARN": "Forewarn",
    "ABILITY_UNAWARE": "Unaware",
    "ABILITY_TINTED_LENS": "Tinted Lens",
    "ABILITY_FILTER": "Filter",
    "ABILITY_SLOW_START": "Slow Start",
    "ABILITY_SCRAPPY": "Scrappy",
    "ABILITY_STORM_DRAIN": "Storm Drain",
    "ABILITY_ICE_BODY": "Ice Body",
    "ABILITY_SOLID_ROCK": "Solid Rock",
    "ABILITY_SNOW_WARNING": "Snow Warning",
    "ABILITY_HONEY_GATHER": "Honey Gather",
    "ABILITY_FRISK": "Frisk",
    "ABILITY_RECKLESS": "Reckless",
    "ABILITY_MULTITYPE": "Multitype",
    "ABILITY_FLOWER_GIFT": "Flower Gift",
    "ABILITY_BAD_DREAMS": "Bad Dreams",
    "ABILITY_PICKPOCKET": "Pickpocket",
    "ABILITY_SHEER_FORCE": "Sheer Force",
    "ABILITY_CONTRARY": "Contrary",
    "ABILITY_UNNERVE": "Unnerve",
    "ABILITY_DEFIANT": "Defiant",
    "ABILITY_DEFEATIST": "Defeatist",
    "ABILITY_CURSED_BODY": "Cursed Body",
    "ABILITY_HEALER": "Healer",
    "ABILITY_FRIEND_GUARD": "Friend Guard",
    "ABILITY_WEAK_ARMOR": "Weak Armor",
    "ABILITY_HEAVY_METAL": "Heavy Metal",
    "ABILITY_LIGHT_METAL": "Light Metal",
    "ABILITY_MULTISCALE": "Multiscale",
    "ABILITY_TOXIC_BOOST": "Toxic Boost",
    "ABILITY_FLARE_BOOST": "Flare Boost",
    "ABILITY_HARVEST": "Harvest",
    "ABILITY_TELEPATHY": "Telepathy",
    "ABILITY_MOODY": "Moody",
    "ABILITY_OVERCOAT": "Overcoat",
    "ABILITY_POISON_TOUCH": "Poison Touch",
    "ABILITY_REGENERATOR": "Regenerator",
    "ABILITY_BIG_PECKS": "Big Pecks",
    "ABILITY_SAND_RUSH": "Sand Rush",
    "ABILITY_WONDER_SKIN": "Wonder Skin",
    "ABILITY_ANALYTIC": "Analytic",
    "ABILITY_ILLUSION": "Illusion",
    "ABILITY_IMPOSTER": "Imposter",
    "ABILITY_INFILTRATOR": "Infiltrator",
    "ABILITY_MUMMY": "Mummy",
    "ABILITY_MOXIE": "Moxie",
    "ABILITY_JUSTIFIED": "Justified",
    "ABILITY_RATTLED": "Rattled",
    "ABILITY_MAGIC_BOUNCE": "Magic Bounce",
    "ABILITY_SAP_SIPPER": "Sap Sipper",
    "ABILITY_PRANKSTER": "Prankster",
    "ABILITY_SAND_FORCE": "Sand Force",
    "ABILITY_IRON_BARBS": "Iron Barbs",
    "ABILITY_ZEN_MODE": "Zen Mode",
    "ABILITY_VICTORY_STAR": "Victory Star",
    "ABILITY_TURBOBLAZE": "Turboblaze",
    "ABILITY_TERAVOLT": "Teravolt",
    "ABILITY_AROMA_VEIL": "Aroma Veil",
    "ABILITY_FLOWER_VEIL": "Flower Veil",
    "ABILITY_CHEEK_POUCH": "Cheek Pouch",
    "ABILITY_PROTEAN": "Protean",
    "ABILITY_FUR_COAT": "Fur Coat",
    "ABILITY_MAGICIAN": "Magician",
    "ABILITY_BULLETPROOF": "Bulletproof",
    "ABILITY_COMPETITIVE": "Competitive",
    "ABILITY_STRONG_JAW": "Strong Jaw",
    "ABILITY_REFRIGERATE": "Refrigerate",
    "ABILITY_SWEET_VEIL": "Sweet Veil",
    "ABILITY_STANCE_CHANGE": "Stance Change",
    "ABILITY_GALE_WINGS": "Gale Wings",
    "ABILITY_MEGA_LAUNCHER": "Mega Launcher",
    "ABILITY_GRASS_PELT": "Grass Pelt",
    "ABILITY_SYMBIOSIS": "Symbiosis",
    "ABILITY_TOUGH_CLAWS": "Tough Claws",
    "ABILITY_PIXILATE": "Pixilate",
    "ABILITY_GOOEY": "Gooey",
    "ABILITY_AERILATE": "Aerilate",
    "ABILITY_PARENTAL_BOND": "Parental Bond",
    "ABILITY_DARK_AURA": "Dark Aura",
    "ABILITY_FAIRY_AURA": "Fairy Aura",
    "ABILITY_AURA_BREAK": "Aura Break",
    "ABILITY_PRIMORDIAL_SEA": "Primordial Sea",
    "ABILITY_DESOLATE_LAND": "Desolate Land",
    "ABILITY_DELTA_STREAM": "Delta Stream",
    "ABILITY_STAMINA": "Stamina",
    "ABILITY_WIMP_OUT": "Wimp Out",
    "ABILITY_EMERGENCY_EXIT": "Emergency Exit",
    "ABILITY_WATER_COMPACTION": "Water Compaction",
    "ABILITY_MERCILESS": "Merciless",
    "ABILITY_SHIELDS_DOWN": "Shields Down",
    "ABILITY_STAKEOUT": "Stakeout",
    "ABILITY_WATER_BUBBLE": "Water Bubble",
    "ABILITY_STEELWORKER": "Steelworker",
    "ABILITY_BERSERK": "Berserk",
    "ABILITY_SLUSH_RUSH": "Slush Rush",
    "ABILITY_LONG_REACH": "Long Reach",
    "ABILITY_LIQUID_VOICE": "Liquid Voice",
    "ABILITY_TRIAGE": "Triage",
    "ABILITY_GALVANIZE": "Galvanize",
    "ABILITY_SURGE_SURFER": "Surge Surfer",
    "ABILITY_SCHOOLING": "Schooling",
    "ABILITY_DISGUISE": "Disguise",
    "ABILITY_BATTLE_BOND": "Battle Bond",
    "ABILITY_POWER_CONSTRUCT": "Power Construct",
    "ABILITY_CORROSION": "Corrosion",
    "ABILITY_COMATOSE": "Comatose",
    "ABILITY_QUEENLY_MAJESTY": "Queenly Majesty",
    "ABILITY_INNARDS_OUT": "Innards Out",
    "ABILITY_DANCER": "Dancer",
    "ABILITY_BATTERY": "Battery",
    "ABILITY_FLUFFY": "Fluffy",
    "ABILITY_DAZZLING": "Dazzling",
    "ABILITY_SOUL_HEART": "Soul Heart",
    "ABILITY_TANGLING_HAIR": "Tangling Hair",
    "ABILITY_RECEIVER": "Receiver",
    "ABILITY_POWER_OF_ALCHEMY": "Power Of Alchemy",
    "ABILITY_BEAST_BOOST": "Beast Boost",
    "ABILITY_RKS_SYSTEM": "Rks System",
    "ABILITY_ELECTRIC_SURGE": "Electric Surge",
    "ABILITY_PSYCHIC_SURGE": "Psychic Surge",
    "ABILITY_MISTY_SURGE": "Misty Surge",
    "ABILITY_GRASSY_SURGE": "Grassy Surge",
    "ABILITY_FULL_METAL_BODY": "Full Metal Body",
    "ABILITY_SHADOW_SHIELD": "Shadow Shield",
    "ABILITY_PRISM_ARMOR": "Prism Armor",
    "ABILITY_NEUROFORCE": "Neuroforce",
    "ABILITY_INTREPID_SWORD": "Intrepid Sword",
    "ABILITY_DAUNTLESS_SHIELD": "Dauntless Shield",
    "ABILITY_LIBERO": "Libero",
    "ABILITY_BALL_FETCH": "Ball Fetch",
    "ABILITY_COTTON_DOWN": "Cotton Down",
    "ABILITY_PROPELLER_TAIL": "Propeller Tail",
    "ABILITY_MIRROR_ARMOR": "Mirror Armor",
    "ABILITY_GULP_MISSILE": "Gulp Missile",
    "ABILITY_STALWART": "Stalwart",
    "ABILITY_STEAM_ENGINE": "Steam Engine",
    "ABILITY_PUNK_ROCK": "Punk Rock",
    "ABILITY_SAND_SPIT": "Sand Spit",
    "ABILITY_ICE_SCALES": "Ice Scales",
    "ABILITY_RIPEN": "Ripen",
    "ABILITY_ICE_FACE": "Ice Face",
    "ABILITY_POWER_SPOT": "Power Spot",
    "ABILITY_MIMICRY": "Mimicry",
    "ABILITY_SCREEN_CLEANER": "Screen Cleaner",
    "ABILITY_STEELY_SPIRIT": "Steely Spirit",
    "ABILITY_PERISH_BODY": "Perish Body",
    "ABILITY_WANDERING_SPIRIT": "Wandering Spirit",
    "ABILITY_GORILLA_TACTICS": "Gorilla Tactics",
    "ABILITY_NEUTRALIZING_GAS": "Neutralizing Gas",
    "ABILITY_PASTEL_VEIL": "Pastel Veil",
    "ABILITY_HUNGER_SWITCH": "Hunger Switch",
    "ABILITY_QUICK_DRAW": "Quick Draw",
    "ABILITY_UNSEEN_FIST": "Unseen Fist",
    "ABILITY_CURIOUS_MEDICINE": "Curious Medicine",
    "ABILITY_TRANSISTOR": "Transistor",
    "ABILITY_DRAGONS_MAW": "Dragons Maw",
    "ABILITY_CHILLING_NEIGH": "Chilling Neigh",
    "ABILITY_GRIM_NEIGH": "Grim Neigh",
    "ABILITY_AS_ONE_ICE_RIDER": "As One Ice Rider",
    "ABILITY_AS_ONE_SHADOW_RIDER": "As One Shadow Rider",
    "ABILITY_LINGERING_AROMA": "Lingering Aroma",
    "ABILITY_SEED_SOWER": "Seed Sower",
    "ABILITY_THERMAL_EXCHANGE": "Thermal Exchange",
    "ABILITY_ANGER_SHELL": "Anger Shell",
    "ABILITY_PURIFYING_SALT": "Purifying Salt",
    "ABILITY_WELL_BAKED_BODY": "Well Baked Body",
    "ABILITY_WIND_RIDER": "Wind Rider",
    "ABILITY_GUARD_DOG": "Guard Dog",
    "ABILITY_ROCKY_PAYLOAD": "Rocky Payload",
    "ABILITY_WIND_POWER": "Wind Power",
    "ABILITY_ZERO_TO_HERO": "Zero To Hero",
    "ABILITY_COMMANDER": "Commander",
    "ABILITY_ELECTROMORPHOSIS": "Electromorphosis",
    "ABILITY_PROTOSYNTHESIS": "Protosynthesis",
    "ABILITY_QUARK_DRIVE": "Quark Drive",
    "ABILITY_GOOD_AS_GOLD": "Good As Gold",
    "ABILITY_VESSEL_OF_RUIN": "Vessel Of Ruin",
    "ABILITY_SWORD_OF_RUIN": "Sword Of Ruin",
    "ABILITY_TABLETS_OF_RUIN": "Tablets Of Ruin",
    "ABILITY_BEADS_OF_RUIN": "Beads Of Ruin",
    "ABILITY_ORICHALCUM_PULSE": "Orichalcum Pulse",
    "ABILITY_HADRON_ENGINE": "Hadron Engine",
    "ABILITY_OPPORTUNIST": "Opportunist",
    "ABILITY_CUD_CHEW": "Cud Chew",
    "ABILITY_SHARPNESS": "Sharpness",
    "ABILITY_SUPREME_OVERLORD": "Supreme Overlord",
    "ABILITY_COSTAR": "Costar",
    "ABILITY_TOXIC_DEBRIS": "Toxic Debris",
    "ABILITY_ARMOR_TAIL": "Armor Tail",
    "ABILITY_EARTH_EATER": "Earth Eater",
    "ABILITY_MYCELIUM_MIGHT": "Mycelium Might",
    "ABILITY_HOSPITALITY": "Hospitality",
    "ABILITY_MINDS_EYE": "Minds Eye",
    "ABILITY_EMBODY_ASPECT_TEAL_MASK": "Embody Aspect Teal Mask",
    "ABILITY_EMBODY_ASPECT_HEARTHFLAME_MASK": "Embody Aspect Hearthflame Mask",
    "ABILITY_EMBODY_ASPECT_WELLSPRING_MASK": "Embody Aspect Wellspring Mask",
    "ABILITY_EMBODY_ASPECT_CORNERSTONE_MASK": "Embody Aspect Cornerstone Mask",
    "ABILITY_TOXIC_CHAIN": "Toxic Chain",
    "ABILITY_SUPERSWEET_SYRUP": "Supersweet Syrup",
    "ABILITY_TERA_SHIFT": "Tera Shift",
    "ABILITY_TERA_SHELL": "Tera Shell",
    "ABILITY_TERAFORM_ZERO": "Teraform Zero",
    "ABILITY_POISON_PUPPETEER": "Poison Puppeteer",
    "ABILITY_MYSTIC_CHARM": "Mystic Charm",
    "ABILITY_LEAF_RUSH": "Leaf Rush",
    "ABILITY_FIERY_CHARGE": "Fiery Charge",
    "ABILITY_ETHEREAL_ECHO": "Ethereal Echo",
    "ABILITY_STRIKER": "Striker",
    "ABILITY_ACID_COAT": "Acid Coat",
    "ABILITY_ECLIPSATE": "Eclipsate",
}