names = {
"ITEM_FIRE_MEMORY": "Fire Memory",
"ITEM_WATER_MEMORY": "Water Memory",
"ITEM_ELECTRIC_MEMORY": "Electric Memory",
"ITEM_GRASS_MEMORY": "Grass Memory",
"ITEM_ICE_MEMORY": "Ice Memory",
"ITEM_FIGHTING_MEMORY": "Fighting Memory",
"ITEM_POISON_MEMORY": "Poison Memory",
"ITEM_GROUND_MEMORY": "Ground Memory",
"ITEM_FLYING_MEMORY": "Flying Memory",
"ITEM_PSYCHIC_MEMORY": "Psychic Memory",
"ITEM_BUG_MEMORY": "Bug Memory",
"ITEM_ROCK_MEMORY": "Rock Memory",
"ITEM_GHOST_MEMORY": "Ghost Memory",
"ITEM_DRAGON_MEMORY": "Dragon Memory",
"ITEM_DARK_MEMORY": "Dark Memory",
"ITEM_STEEL_MEMORY": "Steel Memory",
"ITEM_FAIRY_MEMORY": "Fairy Memory",
"ITEM_NONE": "None",
"ITEM_POKE_BALL": "Poke Ball",
"ITEM_GREAT_BALL": "Great Ball",
"ITEM_ULTRA_BALL": "Ultra Ball",
"ITEM_MASTER_BALL": "Master Ball",
"ITEM_PREMIER_BALL": "Premier Ball",
"ITEM_HEAL_BALL": "Heal Ball",
"ITEM_NET_BALL": "Net Ball",
"ITEM_NEST_BALL": "Nest Ball",
"ITEM_DIVE_BALL": "Dive Ball",
"ITEM_DUSK_BALL": "Dusk Ball",
"ITEM_TIMER_BALL": "Timer Ball",
"ITEM_QUICK_BALL": "Quick Ball",
"ITEM_REPEAT_BALL": "Repeat Ball",
"ITEM_LUXURY_BALL": "Luxury Ball",
"ITEM_LEVEL_BALL": "Level Ball",
"ITEM_LURE_BALL": "Lure Ball",
"ITEM_MOON_BALL": "Moon Ball",
"ITEM_FRIEND_BALL": "Friend Ball",
"ITEM_LOVE_BALL": "Love Ball",
"ITEM_FAST_BALL": "Fast Ball",
"ITEM_HEAVY_BALL": "Heavy Ball",
"ITEM_DREAM_BALL": "Dream Ball",
"ITEM_SAFARI_BALL": "Safari Ball",
"ITEM_SPORT_BALL": "Sport Ball",
"ITEM_PARK_BALL": "Park Ball",
"ITEM_BEAST_BALL": "Beast Ball",
"ITEM_CHERISH_BALL": "Cherish Ball",
"ITEM_POTION": "Potion",
"ITEM_SUPER_POTION": "Super Potion",
"ITEM_HYPER_POTION": "Hyper Potion",
"ITEM_MAX_POTION": "Max Potion",
"ITEM_FULL_RESTORE": "Full Restore",
"ITEM_REVIVE": "Revive",
"ITEM_MAX_REVIVE": "Max Revive",
"ITEM_FRESH_WATER": "Fresh Water",
"ITEM_SODA_POP": "Soda Pop",
"ITEM_LEMONADE": "Lemonade",
"ITEM_MOOMOO_MILK": "Moomoo Milk",
"ITEM_ENERGY_POWDER": "Energy Powder",
"ITEM_ENERGY_ROOT": "Energy Root",
"ITEM_HEAL_POWDER": "Heal Powder",
"ITEM_REVIVAL_HERB": "Revival Herb",
"ITEM_ANTIDOTE": "Antidote",
"ITEM_PARALYZE_HEAL": "Paralyze Heal",
"ITEM_BURN_HEAL": "Burn Heal",
"ITEM_ICE_HEAL": "Ice Heal",
"ITEM_AWAKENING": "Awakening",
"ITEM_FULL_HEAL": "Full Heal",
"ITEM_ETHER": "Ether",
"ITEM_MAX_ETHER": "Max Ether",
"ITEM_ELIXIR": "Elixir",
"ITEM_MAX_ELIXIR": "Max Elixir",
"ITEM_BERRY_JUICE": "Berry Juice",
"ITEM_SACRED_ASH": "Sacred Ash",
"ITEM_SWEET_HEART": "Sweet Heart",
"ITEM_MAX_HONEY": "Max Honey",
"ITEM_PEWTER_CRUNCHIES": "Pewter Crunchies",
"ITEM_RAGE_CANDY_BAR": "Rage Candy Bar",
"ITEM_LAVA_COOKIE": "Lava Cookie",
"ITEM_OLD_GATEAU": "Old Gateau",
"ITEM_CASTELIACONE": "Casteliacone",
"ITEM_LUMIOSE_GALETTE": "Lumiose Galette",
"ITEM_SHALOUR_SABLE": "Shalour Sable",
"ITEM_BIG_MALASADA": "Big Malasada",
"ITEM_HP_UP": "Hp Up",
"ITEM_PROTEIN": "Protein",
"ITEM_IRON": "Iron",
"ITEM_CALCIUM": "Calcium",
"ITEM_ZINC": "Zinc",
"ITEM_CARBOS": "Carbos",
"ITEM_PP_UP": "Pp Up",
"ITEM_PP_MAX": "Pp Max",
"ITEM_HEALTH_FEATHER": "Health Feather",
"ITEM_MUSCLE_FEATHER": "Muscle Feather",
"ITEM_RESIST_FEATHER": "Resist Feather",
"ITEM_GENIUS_FEATHER": "Genius Feather",
"ITEM_CLEVER_FEATHER": "Clever Feather",
"ITEM_SWIFT_FEATHER": "Swift Feather",
"ITEM_ABILITY_CAPSULE": "Ability Capsule",
"ITEM_ABILITY_PATCH": "Ability Patch",
"ITEM_LONELY_MINT": "Lonely Mint",
"ITEM_ADAMANT_MINT": "Adamant Mint",
"ITEM_NAUGHTY_MINT": "Naughty Mint",
"ITEM_BRAVE_MINT": "Brave Mint",
"ITEM_BOLD_MINT": "Bold Mint",
"ITEM_IMPISH_MINT": "Impish Mint",
"ITEM_LAX_MINT": "Lax Mint",
"ITEM_RELAXED_MINT": "Relaxed Mint",
"ITEM_MODEST_MINT": "Modest Mint",
"ITEM_MILD_MINT": "Mild Mint",
"ITEM_RASH_MINT": "Rash Mint",
"ITEM_QUIET_MINT": "Quiet Mint",
"ITEM_CALM_MINT": "Calm Mint",
"ITEM_GENTLE_MINT": "Gentle Mint",
"ITEM_CAREFUL_MINT": "Careful Mint",
"ITEM_SASSY_MINT": "Sassy Mint",
"ITEM_TIMID_MINT": "Timid Mint",
"ITEM_HASTY_MINT": "Hasty Mint",
"ITEM_JOLLY_MINT": "Jolly Mint",
"ITEM_NAIVE_MINT": "Naive Mint",
"ITEM_SERIOUS_MINT": "Serious Mint",
"ITEM_RARE_CANDY": "Rare Candy",
"ITEM_EXP_CANDY_XS": "Exp Candy Xs",
"ITEM_EXP_CANDY_S": "Exp Candy S",
"ITEM_EXP_CANDY_M": "Exp Candy M",
"ITEM_EXP_CANDY_L": "Exp Candy L",
"ITEM_EXP_CANDY_XL": "Exp Candy Xl",
"ITEM_DYNAMAX_CANDY": "Dynamax Candy",
"ITEM_BLUE_FLUTE": "Blue Flute",
"ITEM_YELLOW_FLUTE": "Yellow Flute",
"ITEM_RED_FLUTE": "Red Flute",
"ITEM_BLACK_FLUTE": "Black Flute",
"ITEM_WHITE_FLUTE": "White Flute",
"ITEM_REPEL": "Repel",
"ITEM_SUPER_REPEL": "Super Repel",
"ITEM_MAX_REPEL": "Max Repel",
"ITEM_LURE": "Lure",
"ITEM_SUPER_LURE": "Super Lure",
"ITEM_MAX_LURE": "Max Lure",
"ITEM_ESCAPE_ROPE": "Escape Rope",
"ITEM_X_ATTACK": "X Attack",
"ITEM_X_DEFENSE": "X Defense",
"ITEM_X_SP_ATK": "X Sp Atk",
"ITEM_X_SP_DEF": "X Sp Def",
"ITEM_X_SPEED": "X Speed",
"ITEM_X_ACCURACY": "X Accuracy",
"ITEM_BOTTLE_CAP": "Bottle Cap",
"ITEM_GOLD_BOTTLE_CAP": "Gold Bottle Cap",
"ITEM_NUGGET": "Nugget",
"ITEM_BIG_NUGGET": "Big Nugget",
"ITEM_TINY_MUSHROOM": "Tiny Mushroom",
"ITEM_BIG_MUSHROOM": "Big Mushroom",
"ITEM_BALM_MUSHROOM": "Balm Mushroom",
"ITEM_PEARL": "Pearl",
"ITEM_BIG_PEARL": "Big Pearl",
"ITEM_PEARL_STRING": "Pearl String",
"ITEM_STARDUST": "Stardust",
"ITEM_STAR_PIECE": "Star Piece",
"ITEM_COMET_SHARD": "Comet Shard",
"ITEM_SHOAL_SALT": "Shoal Salt",
"ITEM_SHOAL_SHELL": "Shoal Shell",
"ITEM_RED_SHARD": "Red Shard",
"ITEM_BLUE_SHARD": "Blue Shard",
"ITEM_YELLOW_SHARD": "Yellow Shard",
"ITEM_GREEN_SHARD": "Green Shard",
"ITEM_HEART_SCALE": "Heart Scale",
"ITEM_HONEY": "Honey",
"ITEM_RARE_BONE": "Rare Bone",
"ITEM_ODD_KEYSTONE": "Odd Keystone",
"ITEM_PRETTY_FEATHER": "Pretty Feather",
"ITEM_RELIC_COPPER": "Relic Copper",
"ITEM_RELIC_SILVER": "Relic Silver",
"ITEM_RELIC_GOLD": "Relic Gold",
"ITEM_RELIC_VASE": "Relic Vase",
"ITEM_RELIC_BAND": "Relic Band",
"ITEM_RELIC_STATUE": "Relic Statue",
"ITEM_RELIC_CROWN": "Relic Crown",
"ITEM_STRANGE_SOUVENIR": "Strange Souvenir",
"ITEM_NORMAL_GEM": "Normal Gem",
"ITEM_FIRE_GEM": "Fire Gem",
"ITEM_WATER_GEM": "Water Gem",
"ITEM_ELECTRIC_GEM": "Electric Gem",
"ITEM_GRASS_GEM": "Grass Gem",
"ITEM_ICE_GEM": "Ice Gem",
"ITEM_FIGHTING_GEM": "Fighting Gem",
"ITEM_POISON_GEM": "Poison Gem",
"ITEM_GROUND_GEM": "Ground Gem",
"ITEM_FLYING_GEM": "Flying Gem",
"ITEM_PSYCHIC_GEM": "Psychic Gem",
"ITEM_BUG_GEM": "Bug Gem",
"ITEM_ROCK_GEM": "Rock Gem",
"ITEM_GHOST_GEM": "Ghost Gem",
"ITEM_DRAGON_GEM": "Dragon Gem",
"ITEM_DARK_GEM": "Dark Gem",
"ITEM_STEEL_GEM": "Steel Gem",
"ITEM_FAIRY_GEM": "Fairy Gem",
"ITEM_NORMALIUM_Z": "Normalium Z",
"ITEM_FIRIUM_Z": "Firium Z",
"ITEM_WATERIUM_Z": "Waterium Z",
"ITEM_ELECTRIUM_Z": "Electrium Z",
"ITEM_GRASSIUM_Z": "Grassium Z",
"ITEM_ICIUM_Z": "Icium Z",
"ITEM_FIGHTINIUM_Z": "Fightinium Z",
"ITEM_POISONIUM_Z": "Poisonium Z",
"ITEM_GROUNDIUM_Z": "Groundium Z",
"ITEM_FLYINIUM_Z": "Flyinium Z",
"ITEM_PSYCHIUM_Z": "Psychium Z",
"ITEM_BUGINIUM_Z": "Buginium Z",
"ITEM_ROCKIUM_Z": "Rockium Z",
"ITEM_GHOSTIUM_Z": "Ghostium Z",
"ITEM_DRAGONIUM_Z": "Dragonium Z",
"ITEM_DARKINIUM_Z": "Darkinium Z",
"ITEM_STEELIUM_Z": "Steelium Z",
"ITEM_FAIRIUM_Z": "Fairium Z",
"ITEM_PIKANIUM_Z": "Pikanium Z",
"ITEM_EEVIUM_Z": "Eevium Z",
"ITEM_SNORLIUM_Z": "Snorlium Z",
"ITEM_MEWNIUM_Z": "Mewnium Z",
"ITEM_DECIDIUM_Z": "Decidium Z",
"ITEM_INCINIUM_Z": "Incinium Z",
"ITEM_PRIMARIUM_Z": "Primarium Z",
"ITEM_LYCANIUM_Z": "Lycanium Z",
"ITEM_MIMIKIUM_Z": "Mimikium Z",
"ITEM_KOMMONIUM_Z": "Kommonium Z",
"ITEM_TAPUNIUM_Z": "Tapunium Z",
"ITEM_SOLGANIUM_Z": "Solganium Z",
"ITEM_LUNALIUM_Z": "Lunalium Z",
"ITEM_MARSHADIUM_Z": "Marshadium Z",
"ITEM_ALORAICHIUM_Z": "Aloraichium Z",
"ITEM_PIKASHUNIUM_Z": "Pikashunium Z",
"ITEM_ULTRANECROZIUM_Z": "Ultranecrozium Z",
"ITEM_LIGHT_BALL": "Light Ball",
"ITEM_LEEK": "Leek",
"ITEM_THICK_CLUB": "Thick Club",
"ITEM_LUCKY_PUNCH": "Lucky Punch",
"ITEM_METAL_POWDER": "Metal Powder",
"ITEM_QUICK_POWDER": "Quick Powder",
"ITEM_DEEP_SEA_SCALE": "Deep Sea Scale",
"ITEM_DEEP_SEA_TOOTH": "Deep Sea Tooth",
"ITEM_SOUL_DEW": "Soul Dew",
"ITEM_ADAMANT_ORB": "Adamant Orb",
"ITEM_LUSTROUS_ORB": "Lustrous Orb",
"ITEM_GRISEOUS_ORB": "Griseous Orb",
"ITEM_SEA_INCENSE": "Sea Incense",
"ITEM_LAX_INCENSE": "Lax Incense",
"ITEM_ODD_INCENSE": "Odd Incense",
"ITEM_ROCK_INCENSE": "Rock Incense",
"ITEM_FULL_INCENSE": "Full Incense",
"ITEM_WAVE_INCENSE": "Wave Incense",
"ITEM_ROSE_INCENSE": "Rose Incense",
"ITEM_LUCK_INCENSE": "Luck Incense",
"ITEM_PURE_INCENSE": "Pure Incense",
"ITEM_RED_SCARF": "Red Scarf",
"ITEM_BLUE_SCARF": "Blue Scarf",
"ITEM_PINK_SCARF": "Pink Scarf",
"ITEM_GREEN_SCARF": "Green Scarf",
"ITEM_YELLOW_SCARF": "Yellow Scarf",
"ITEM_MACHO_BRACE": "Macho Brace",
"ITEM_POWER_WEIGHT": "Power Weight",
"ITEM_POWER_BRACER": "Power Bracer",
"ITEM_POWER_BELT": "Power Belt",
"ITEM_POWER_LENS": "Power Lens",
"ITEM_POWER_BAND": "Power Band",
"ITEM_POWER_ANKLET": "Power Anklet",
"ITEM_SILK_SCARF": "Silk Scarf",
"ITEM_CHARCOAL": "Charcoal",
"ITEM_MYSTIC_WATER": "Mystic Water",
"ITEM_MAGNET": "Magnet",
"ITEM_MIRACLE_SEED": "Miracle Seed",
"ITEM_NEVER_MELT_ICE": "Never Melt Ice",
"ITEM_BLACK_BELT": "Black Belt",
"ITEM_POISON_BARB": "Poison Barb",
"ITEM_SOFT_SAND": "Soft Sand",
"ITEM_SHARP_BEAK": "Sharp Beak",
"ITEM_TWISTED_SPOON": "Twisted Spoon",
"ITEM_SILVER_POWDER": "Silver Powder",
"ITEM_HARD_STONE": "Hard Stone",
"ITEM_SPELL_TAG": "Spell Tag",
"ITEM_DRAGON_FANG": "Dragon Fang",
"ITEM_BLACK_GLASSES": "Black Glasses",
"ITEM_METAL_COAT": "Metal Coat",
"ITEM_CHOICE_BAND": "Choice Band",
"ITEM_CHOICE_SPECS": "Choice Specs",
"ITEM_CHOICE_SCARF": "Choice Scarf",
"ITEM_FLAME_ORB": "Flame Orb",
"ITEM_TOXIC_ORB": "Toxic Orb",
"ITEM_DAMP_ROCK": "Damp Rock",
"ITEM_HEAT_ROCK": "Heat Rock",
"ITEM_SMOOTH_ROCK": "Smooth Rock",
"ITEM_ICY_ROCK": "Icy Rock",
"ITEM_ELECTRIC_SEED": "Electric Seed",
"ITEM_PSYCHIC_SEED": "Psychic Seed",
"ITEM_MISTY_SEED": "Misty Seed",
"ITEM_GRASSY_SEED": "Grassy Seed",
"ITEM_ABSORB_BULB": "Absorb Bulb",
"ITEM_CELL_BATTERY": "Cell Battery",
"ITEM_LUMINOUS_MOSS": "Luminous Moss",
"ITEM_SNOWBALL": "Snowball",
"ITEM_BRIGHT_POWDER": "Bright Powder",
"ITEM_WHITE_HERB": "White Herb",
"ITEM_EXP_SHARE": "Exp Share",
"ITEM_QUICK_CLAW": "Quick Claw",
"ITEM_SOOTHE_BELL": "Soothe Bell",
"ITEM_MENTAL_HERB": "Mental Herb",
"ITEM_KINGS_ROCK": "Kings Rock",
"ITEM_AMULET_COIN": "Amulet Coin",
"ITEM_CLEANSE_TAG": "Cleanse Tag",
"ITEM_SMOKE_BALL": "Smoke Ball",
"ITEM_FOCUS_BAND": "Focus Band",
"ITEM_LUCKY_EGG": "Lucky Egg",
"ITEM_SCOPE_LENS": "Scope Lens",
"ITEM_LEFTOVERS": "Leftovers",
"ITEM_SHELL_BELL": "Shell Bell",
"ITEM_WIDE_LENS": "Wide Lens",
"ITEM_MUSCLE_BAND": "Muscle Band",
"ITEM_WISE_GLASSES": "Wise Glasses",
"ITEM_EXPERT_BELT": "Expert Belt",
"ITEM_LIGHT_CLAY": "Light Clay",
"ITEM_LIFE_ORB": "Life Orb",
"ITEM_POWER_HERB": "Power Herb",
"ITEM_FOCUS_SASH": "Focus Sash",
"ITEM_ZOOM_LENS": "Zoom Lens",
"ITEM_METRONOME": "Metronome",
"ITEM_IRON_BALL": "Iron Ball",
"ITEM_LAGGING_TAIL": "Lagging Tail",
"ITEM_DESTINY_KNOT": "Destiny Knot",
"ITEM_BLACK_SLUDGE": "Black Sludge",
"ITEM_GRIP_CLAW": "Grip Claw",
"ITEM_STICKY_BARB": "Sticky Barb",
"ITEM_SHED_SHELL": "Shed Shell",
"ITEM_BIG_ROOT": "Big Root",
"ITEM_RAZOR_CLAW": "Razor Claw",
"ITEM_RAZOR_FANG": "Razor Fang",
"ITEM_EVIOLITE": "Eviolite",
"ITEM_FLOAT_STONE": "Float Stone",
"ITEM_ROCKY_HELMET": "Rocky Helmet",
"ITEM_AIR_BALLOON": "Air Balloon",
"ITEM_RED_CARD": "Red Card",
"ITEM_RING_TARGET": "Ring Target",
"ITEM_BINDING_BAND": "Binding Band",
"ITEM_EJECT_BUTTON": "Eject Button",
"ITEM_WEAKNESS_POLICY": "Weakness Policy",
"ITEM_ASSAULT_VEST": "Assault Vest",
"ITEM_SAFETY_GOGGLES": "Safety Goggles",
"ITEM_ADRENALINE_ORB": "Adrenaline Orb",
"ITEM_TERRAIN_EXTENDER": "Terrain Extender",
"ITEM_PROTECTIVE_PADS": "Protective Pads",
"ITEM_THROAT_SPRAY": "Throat Spray",
"ITEM_EJECT_PACK": "Eject Pack",
"ITEM_HEAVY_DUTY_BOOTS": "Heavy Duty Boots",
"ITEM_BLUNDER_POLICY": "Blunder Policy",
"ITEM_ROOM_SERVICE": "Room Service",
"ITEM_UTILITY_UMBRELLA": "Utility Umbrella",
"ITEM_CHERI_BERRY": "Cheri Berry",
"ITEM_CHESTO_BERRY": "Chesto Berry",
"ITEM_PECHA_BERRY": "Pecha Berry",
"ITEM_RAWST_BERRY": "Rawst Berry",
"ITEM_ASPEAR_BERRY": "Aspear Berry",
"ITEM_LEPPA_BERRY": "Leppa Berry",
"ITEM_ORAN_BERRY": "Oran Berry",
"ITEM_PERSIM_BERRY": "Persim Berry",
"ITEM_LUM_BERRY": "Lum Berry",
"ITEM_SITRUS_BERRY": "Sitrus Berry",
"ITEM_FIGY_BERRY": "Figy Berry",
"ITEM_WIKI_BERRY": "Wiki Berry",
"ITEM_MAGO_BERRY": "Mago Berry",
"ITEM_AGUAV_BERRY": "Aguav Berry",
"ITEM_IAPAPA_BERRY": "Iapapa Berry",
"ITEM_RAZZ_BERRY": "Razz Berry",
"ITEM_BLUK_BERRY": "Bluk Berry",
"ITEM_NANAB_BERRY": "Nanab Berry",
"ITEM_WEPEAR_BERRY": "Wepear Berry",
"ITEM_PINAP_BERRY": "Pinap Berry",
"ITEM_POMEG_BERRY": "Pomeg Berry",
"ITEM_KELPSY_BERRY": "Kelpsy Berry",
"ITEM_QUALOT_BERRY": "Qualot Berry",
"ITEM_HONDEW_BERRY": "Hondew Berry",
"ITEM_GREPA_BERRY": "Grepa Berry",
"ITEM_TAMATO_BERRY": "Tamato Berry",
"ITEM_CORNN_BERRY": "Cornn Berry",
"ITEM_MAGOST_BERRY": "Magost Berry",
"ITEM_RABUTA_BERRY": "Rabuta Berry",
"ITEM_NOMEL_BERRY": "Nomel Berry",
"ITEM_SPELON_BERRY": "Spelon Berry",
"ITEM_PAMTRE_BERRY": "Pamtre Berry",
"ITEM_WATMEL_BERRY": "Watmel Berry",
"ITEM_DURIN_BERRY": "Durin Berry",
"ITEM_BELUE_BERRY": "Belue Berry",
"ITEM_CHILAN_BERRY": "Chilan Berry",
"ITEM_OCCA_BERRY": "Occa Berry",
"ITEM_PASSHO_BERRY": "Passho Berry",
"ITEM_WACAN_BERRY": "Wacan Berry",
"ITEM_RINDO_BERRY": "Rindo Berry",
"ITEM_YACHE_BERRY": "Yache Berry",
"ITEM_CHOPLE_BERRY": "Chople Berry",
"ITEM_KEBIA_BERRY": "Kebia Berry",
"ITEM_SHUCA_BERRY": "Shuca Berry",
"ITEM_COBA_BERRY": "Coba Berry",
"ITEM_PAYAPA_BERRY": "Payapa Berry",
"ITEM_TANGA_BERRY": "Tanga Berry",
"ITEM_CHARTI_BERRY": "Charti Berry",
"ITEM_KASIB_BERRY": "Kasib Berry",
"ITEM_HABAN_BERRY": "Haban Berry",
"ITEM_COLBUR_BERRY": "Colbur Berry",
"ITEM_BABIRI_BERRY": "Babiri Berry",
"ITEM_ROSELI_BERRY": "Roseli Berry",
"ITEM_LIECHI_BERRY": "Liechi Berry",
"ITEM_GANLON_BERRY": "Ganlon Berry",
"ITEM_SALAC_BERRY": "Salac Berry",
"ITEM_PETAYA_BERRY": "Petaya Berry",
"ITEM_APICOT_BERRY": "Apicot Berry",
"ITEM_LANSAT_BERRY": "Lansat Berry",
"ITEM_STARF_BERRY": "Starf Berry",
"ITEM_ENIGMA_BERRY": "Enigma Berry",
"ITEM_MICLE_BERRY": "Micle Berry",
"ITEM_CUSTAP_BERRY": "Custap Berry",
"ITEM_JABOCA_BERRY": "Jaboca Berry",
"ITEM_ROWAP_BERRY": "Rowap Berry",
"ITEM_KEE_BERRY": "Kee Berry",
"ITEM_MARANGA_BERRY": "Maranga Berry",
"ITEM_ENIGMA_BERRY_E_READER": "Enigma Berry E Reader",
"ITEM_ABILITY_SHIELD": "Ability Shield",
"ITEM_CLEAR_AMULET": "Clear Amulet",
"ITEM_PUNCHING_GLOVE": "Punching Glove",
"ITEM_COVERT_CLOAK": "Covert Cloak",
"ITEM_LOADED_DICE": "Loaded Dice",
"ITEM_AUSPICIOUS_ARMOR": "Auspicious Armor",
"ITEM_BOOSTER_ENERGY": "Booster Energy",
"ITEM_BIG_BAMBOO_SHOOT": "Big Bamboo Shoot",
"ITEM_GIMMIGHOUL_COIN": "Gimmighoul Coin",
"ITEM_LEADERS_CREST": "Leaders Crest",
"ITEM_MALICIOUS_ARMOR": "Malicious Armor",
"ITEM_MIRROR_HERB": "Mirror Herb",
"ITEM_SCROLL_OF_DARKNESS": "Scroll Of Darkness",
"ITEM_SCROLL_OF_WATERS": "Scroll Of Waters",
"ITEM_TERA_ORB": "Tera Orb",
"ITEM_TINY_BAMBOO_SHOOT": "Tiny Bamboo Shoot",
"ITEM_BUG_TERA_SHARD": "Bug Tera Shard",
"ITEM_DARK_TERA_SHARD": "Dark Tera Shard",
"ITEM_DRAGON_TERA_SHARD": "Dragon Tera Shard",
"ITEM_ELECTRIC_TERA_SHARD": "Electric Tera Shard",
"ITEM_FAIRY_TERA_SHARD": "Fairy Tera Shard",
"ITEM_FIGHTING_TERA_SHARD": "Fighting Tera Shard",
"ITEM_FIRE_TERA_SHARD": "Fire Tera Shard",
"ITEM_FLYING_TERA_SHARD": "Flying Tera Shard",
"ITEM_GHOST_TERA_SHARD": "Ghost Tera Shard",
"ITEM_GRASS_TERA_SHARD": "Grass Tera Shard",
"ITEM_GROUND_TERA_SHARD": "Ground Tera Shard",
"ITEM_ICE_TERA_SHARD": "Ice Tera Shard",
"ITEM_NORMAL_TERA_SHARD": "Normal Tera Shard",
"ITEM_POISON_TERA_SHARD": "Poison Tera Shard",
"ITEM_PSYCHIC_TERA_SHARD": "Psychic Tera Shard",
"ITEM_ROCK_TERA_SHARD": "Rock Tera Shard",
"ITEM_STEEL_TERA_SHARD": "Steel Tera Shard",
"ITEM_WATER_TERA_SHARD": "Water Tera Shard",
"ITEM_ADAMANT_CRYSTAL": "Adamant Crystal",
"ITEM_GRISEOUS_CORE": "Griseous Core",
"ITEM_LUSTROUS_GLOBE": "Lustrous Globe",
"ITEM_BLACK_AUGURITE": "Black Augurite",
"ITEM_LINKING_CORD": "Linking Cord",
"ITEM_PEAT_BLOCK": "Peat Block",
"ITEM_BERSERK_GENE": "Berserk Gene",
"ITEM_FAIRY_FEATHER": "Fairy Feather",
"ITEM_SYRUPY_APPLE": "Syrupy Apple",
"ITEM_UNREMARKABLE_TEACUP": "Unremarkable Teacup",
"ITEM_MASTERPIECE_TEACUP": "Masterpiece Teacup",
"ITEM_CORNERSTONE_MASK": "Cornerstone Mask",
"ITEM_WELLSPRING_MASK": "Wellspring Mask",
"ITEM_HEARTHFLAME_MASK": "Hearthflame Mask",
"ITEM_HEALTH_MOCHI": "Health Mochi",
"ITEM_MUSCLE_MOCHI": "Muscle Mochi",
"ITEM_RESIST_MOCHI": "Resist Mochi",
"ITEM_GENIUS_MOCHI": "Genius Mochi",
"ITEM_CLEVER_MOCHI": "Clever Mochi",
"ITEM_SWIFT_MOCHI": "Swift Mochi",
"ITEM_FRESH_START_MOCHI": "Fresh Start Mochi",
"ITEM_GLIMMERING_CHARM": "Glimmering Charm",
"ITEM_METAL_ALLOY": "Metal Alloy",
"ITEM_STELLAR_TERA_SHARD": "Stellar Tera Shard",
"ITEM_JUBILIFE_MUFFIN": "Jubilife Muffin",
"ITEM_REMEDY": "Remedy",
"ITEM_FINE_REMEDY": "Fine Remedy",
"ITEM_SUPERB_REMEDY": "Superb Remedy",
"ITEM_AUX_EVASION": "Aux Evasion",
"ITEM_AUX_GUARD": "Aux Guard",
"ITEM_AUX_POWER": "Aux Power",
"ITEM_AUX_POWERGUARD": "Aux Powerguard",
"ITEM_CHOICE_DUMPLING": "Choice Dumpling",
"ITEM_SWAP_SNACK": "Swap Snack",
"ITEM_TWICE_SPICED_RADISH": "Twice Spiced Radish",
"ITEM_POKESHI_DOLL": "Pokeshi Doll",
"ITEM_SHOCK_DRIVE": "Shock Drive",
}