names = {
    "MOVE_NONE": "None",
    "MOVE_POUND": "Pound",
    "MOVE_KARATE_CHOP": "Karate Chop",
    "MOVE_DOUBLE_SLAP": "Double Slap",
    "MOVE_COMET_PUNCH": "Comet Punch",
    "MOVE_MEGA_PUNCH": "Mega Punch",
    "MOVE_PAY_DAY": "Pay Day",
    "MOVE_FIRE_PUNCH": "Fire Punch",
    "MOVE_ICE_PUNCH": "Ice Punch",
    "MOVE_THUNDER_PUNCH": "Thunder Punch",
    "MOVE_SCRATCH": "Scratch",
    "MOVE_VISE_GRIP": "Vise Grip",
    "MOVE_GUILLOTINE": "Guillotine",
    "MOVE_RAZOR_WIND": "Razor Wind",
    "MOVE_SWORDS_DANCE": "Swords Dance",
    "MOVE_CUT": "Cut",
    "MOVE_GUST": "Gust",
    "MOVE_WING_ATTACK": "Wing Attack",
    "MOVE_WHIRLWIND": "Whirlwind",
    "MOVE_FLY": "Fly",
    "MOVE_BIND": "Bind",
    "MOVE_SLAM": "Slam",
    "MOVE_VINE_WHIP": "Vine Whip",
    "MOVE_STOMP": "Stomp",
    "MOVE_DOUBLE_KICK": "Double Kick",
    "MOVE_MEGA_KICK": "Mega Kick",
    "MOVE_JUMP_KICK": "Jump Kick",
    "MOVE_ROLLING_KICK": "Rolling Kick",
    "MOVE_SAND_ATTACK": "Sand Attack",
    "MOVE_HEADBUTT": "Headbutt",
    "MOVE_HORN_ATTACK": "Horn Attack",
    "MOVE_FURY_ATTACK": "Fury Attack",
    "MOVE_HORN_DRILL": "Horn Drill",
    "MOVE_TACKLE": "Tackle",
    "MOVE_BODY_SLAM": "Body Slam",
    "MOVE_WRAP": "Wrap",
    "MOVE_TAKE_DOWN": "Take Down",
    "MOVE_THRASH": "Thrash",
    "MOVE_DOUBLE_EDGE": "Double-Edge",
    "MOVE_TAIL_WHIP": "Tail Whip",
    "MOVE_POISON_STING": "Poison Sting",
    "MOVE_TWINEEDLE": "Twineedle",
    "MOVE_PIN_MISSILE": "Pin Missile",
    "MOVE_LEER": "Leer",
    "MOVE_BITE": "Bite",
    "MOVE_GROWL": "Growl",
    "MOVE_ROAR": "Roar",
    "MOVE_SING": "Sing",
    "MOVE_SUPERSONIC": "Supersonic",
    "MOVE_SONIC_BOOM": "Sonic Boom",
    "MOVE_DISABLE": "Disable",
    "MOVE_ACID": "Acid",
    "MOVE_EMBER": "Ember",
    "MOVE_FLAMETHROWER": "Flamethrower",
    "MOVE_MIST": "Mist",
    "MOVE_WATER_GUN": "Water Gun",
    "MOVE_HYDRO_PUMP": "Hydro Pump",
    "MOVE_SURF": "Surf",
    "MOVE_ICE_BEAM": "Ice Beam",
    "MOVE_BLIZZARD": "Blizzard",
    "MOVE_PSYBEAM": "Psybeam",
    "MOVE_BUBBLE_BEAM": "Bubble Beam",
    "MOVE_AURORA_BEAM": "Aurora Beam",
    "MOVE_HYPER_BEAM": "Hyper Beam",
    "MOVE_PECK": "Peck",
    "MOVE_DRILL_PECK": "Drill Peck",
    "MOVE_SUBMISSION": "Submission",
    "MOVE_LOW_KICK": "Low Kick",
    "MOVE_COUNTER": "Counter",
    "MOVE_SEISMIC_TOSS": "Seismic Toss",
    "MOVE_STRENGTH": "Strength",
    "MOVE_ABSORB": "Absorb",
    "MOVE_MEGA_DRAIN": "Mega Drain",
    "MOVE_LEECH_SEED": "Leech Seed",
    "MOVE_GROWTH": "Growth",
    "MOVE_RAZOR_LEAF": "Razor Leaf",
    "MOVE_SOLAR_BEAM": "Solar Beam",
    "MOVE_POISON_POWDER": "Poison Powder",
    "MOVE_STUN_SPORE": "Stun Spore",
    "MOVE_SLEEP_POWDER": "Sleep Powder",
    "MOVE_PETAL_DANCE": "Petal Dance",
    "MOVE_STRING_SHOT": "String Shot",
    "MOVE_DRAGON_RAGE": "Dragon Rage",
    "MOVE_FIRE_SPIN": "Fire Spin",
    "MOVE_THUNDER_SHOCK": "Thunder Shock",
    "MOVE_THUNDERBOLT": "Thunderbolt",
    "MOVE_THUNDER_WAVE": "Thunder Wave",
    "MOVE_THUNDER": "Thunder",
    "MOVE_ROCK_THROW": "Rock Throw",
    "MOVE_EARTHQUAKE": "Earthquake",
    "MOVE_FISSURE": "Fissure",
    "MOVE_DIG": "Dig",
    "MOVE_TOXIC": "Toxic",
    "MOVE_CONFUSION": "Confusion",
    "MOVE_PSYCHIC": "Psychic",
    "MOVE_HYPNOSIS": "Hypnosis",
    "MOVE_MEDITATE": "Meditate",
    "MOVE_AGILITY": "Agility",
    "MOVE_QUICK_ATTACK": "Quick Attack",
    "MOVE_RAGE": "Rage",
    "MOVE_TELEPORT": "Teleport",
    "MOVE_NIGHT_SHADE": "Night Shade",
    "MOVE_MIMIC": "Mimic",
    "MOVE_SCREECH": "Screech",
    "MOVE_DOUBLE_TEAM": "Double Team",
    "MOVE_RECOVER": "Recover",
    "MOVE_HARDEN": "Harden",
    "MOVE_MINIMIZE": "Minimize",
    "MOVE_SMOKESCREEN": "Smokescreen",
    "MOVE_CONFUSE_RAY": "Confuse Ray",
    "MOVE_WITHDRAW": "Withdraw",
    "MOVE_DEFENSE_CURL": "Defense Curl",
    "MOVE_BARRIER": "Barrier",
    "MOVE_LIGHT_SCREEN": "Light Screen",
    "MOVE_HAZE": "Haze",
    "MOVE_REFLECT": "Reflect",
    "MOVE_FOCUS_ENERGY": "Focus Energy",
    "MOVE_BIDE": "Bide",
    "MOVE_METRONOME": "Metronome",
    "MOVE_MIRROR_MOVE": "Mirror Move",
    "MOVE_SELF_DESTRUCT": "Self Destruct",
    "MOVE_EGG_BOMB": "Egg Bomb",
    "MOVE_LICK": "Lick",
    "MOVE_SMOG": "Smog",
    "MOVE_SLUDGE": "Sludge",
    "MOVE_BONE_CLUB": "Bone Club",
    "MOVE_FIRE_BLAST": "Fire Blast",
    "MOVE_WATERFALL": "Waterfall",
    "MOVE_CLAMP": "Clamp",
    "MOVE_SWIFT": "Swift",
    "MOVE_SKULL_BASH": "Skull Bash",
    "MOVE_SPIKE_CANNON": "Spike Cannon",
    "MOVE_CONSTRICT": "Constrict",
    "MOVE_AMNESIA": "Amnesia",
    "MOVE_KINESIS": "Kinesis",
    "MOVE_SOFT_BOILED": "Soft Boiled",
    "MOVE_HIGH_JUMP_KICK": "High Jump Kick",
    "MOVE_GLARE": "Glare",
    "MOVE_DREAM_EATER": "Dream Eater",
    "MOVE_POISON_GAS": "Poison Gas",
    "MOVE_BARRAGE": "Barrage",
    "MOVE_LEECH_LIFE": "Leech Life",
    "MOVE_LOVELY_KISS": "Lovely Kiss",
    "MOVE_SKY_ATTACK": "Sky Attack",
    "MOVE_TRANSFORM": "Transform",
    "MOVE_BUBBLE": "Bubble",
    "MOVE_DIZZY_PUNCH": "Dizzy Punch",
    "MOVE_SPORE": "Spore",
    "MOVE_FLASH": "Flash",
    "MOVE_PSYWAVE": "Psywave",
    "MOVE_SPLASH": "Splash",
    "MOVE_ACID_ARMOR": "Acid Armor",
    "MOVE_CRABHAMMER": "Crabhammer",
    "MOVE_EXPLOSION": "Explosion",
    "MOVE_FURY_SWIPES": "Fury Swipes",
    "MOVE_BONEMERANG": "Bonemerang",
    "MOVE_REST": "Rest",
    "MOVE_ROCK_SLIDE": "Rock Slide",
    "MOVE_HYPER_FANG": "Hyper Fang",
    "MOVE_SHARPEN": "Sharpen",
    "MOVE_CONVERSION": "Conversion",
    "MOVE_TRI_ATTACK": "Tri Attack",
    "MOVE_SUPER_FANG": "Super Fang",
    "MOVE_SLASH": "Slash",
    "MOVE_SUBSTITUTE": "Substitute",
    "MOVE_STRUGGLE": "Struggle",
    "MOVE_SKETCH": "Sketch",
    "MOVE_TRIPLE_KICK": "Triple Kick",
    "MOVE_THIEF": "Thief",
    "MOVE_SPIDER_WEB": "Spider Web",
    "MOVE_MIND_READER": "Mind Reader",
    "MOVE_NIGHTMARE": "Nightmare",
    "MOVE_FLAME_WHEEL": "Flame Wheel",
    "MOVE_SNORE": "Snore",
    "MOVE_CURSE": "Curse",
    "MOVE_FLAIL": "Flail",
    "MOVE_CONVERSION_2": "Conversion 2",
    "MOVE_AEROBLAST": "Aeroblast",
    "MOVE_COTTON_SPORE": "Cotton Spore",
    "MOVE_REVERSAL": "Reversal",
    "MOVE_SPITE": "Spite",
    "MOVE_POWDER_SNOW": "Powder Snow",
    "MOVE_PROTECT": "Protect",
    "MOVE_MACH_PUNCH": "Mach Punch",
    "MOVE_SCARY_FACE": "Scary Face",
    "MOVE_FEINT_ATTACK": "Feint Attack",
    "MOVE_SWEET_KISS": "Sweet Kiss",
    "MOVE_BELLY_DRUM": "Belly Drum",
    "MOVE_SLUDGE_BOMB": "Sludge Bomb",
    "MOVE_MUD_SLAP": "Mud Slap",
    "MOVE_OCTAZOOKA": "Octazooka",
    "MOVE_SPIKES": "Spikes",
    "MOVE_ZAP_CANNON": "Zap Cannon",
    "MOVE_FORESIGHT": "Foresight",
    "MOVE_DESTINY_BOND": "Destiny Bond",
    "MOVE_PERISH_SONG": "Perish Song",
    "MOVE_ICY_WIND": "Icy Wind",
    "MOVE_DETECT": "Detect",
    "MOVE_BONE_RUSH": "Bone Rush",
    "MOVE_LOCK_ON": "Lock On",
    "MOVE_OUTRAGE": "Outrage",
    "MOVE_SANDSTORM": "Sandstorm",
    "MOVE_GIGA_DRAIN": "Giga Drain",
    "MOVE_ENDURE": "Endure",
    "MOVE_CHARM": "Charm",
    "MOVE_ROLLOUT": "Rollout",
    "MOVE_FALSE_SWIPE": "False Swipe",
    "MOVE_SWAGGER": "Swagger",
    "MOVE_MILK_DRINK": "Milk Drink",
    "MOVE_SPARK": "Spark",
    "MOVE_FURY_CUTTER": "Fury Cutter",
    "MOVE_STEEL_WING": "Steel Wing",
    "MOVE_MEAN_LOOK": "Mean Look",
    "MOVE_ATTRACT": "Attract",
    "MOVE_SLEEP_TALK": "Sleep Talk",
    "MOVE_HEAL_BELL": "Heal Bell",
    "MOVE_RETURN": "Return",
    "MOVE_PRESENT": "Present",
    "MOVE_FRUSTRATION": "Frustration",
    "MOVE_SAFEGUARD": "Safeguard",
    "MOVE_PAIN_SPLIT": "Pain Split",
    "MOVE_SACRED_FIRE": "Sacred Fire",
    "MOVE_MAGNITUDE": "Magnitude",
    "MOVE_DYNAMIC_PUNCH": "Dynamic Punch",
    "MOVE_MEGAHORN": "Megahorn",
    "MOVE_DRAGON_BREATH": "Dragon Breath",
    "MOVE_BATON_PASS": "Baton Pass",
    "MOVE_ENCORE": "Encore",
    "MOVE_PURSUIT": "Pursuit",
    "MOVE_RAPID_SPIN": "Rapid Spin",
    "MOVE_SWEET_SCENT": "Sweet Scent",
    "MOVE_IRON_TAIL": "Iron Tail",
    "MOVE_METAL_CLAW": "Metal Claw",
    "MOVE_VITAL_THROW": "Vital Throw",
    "MOVE_MORNING_SUN": "Morning Sun",
    "MOVE_SYNTHESIS": "Synthesis",
    "MOVE_MOONLIGHT": "Moonlight",
    "MOVE_HIDDEN_POWER": "Hidden Power",
    "MOVE_HIDDEN_POWER_FIRE": "Hidden Power Fire",
    "MOVE_HIDDEN_POWER_GRASS": "Hidden Power Grass",
    "MOVE_HIDDEN_POWER_ICE": "Hidden Power Ice",
    "MOVE_CROSS_CHOP": "Cross Chop",
    "MOVE_TWISTER": "Twister",
    "MOVE_RAIN_DANCE": "Rain Dance",
    "MOVE_SUNNY_DAY": "Sunny Day",
    "MOVE_CRUNCH": "Crunch",
    "MOVE_MIRROR_COAT": "Mirror Coat",
    "MOVE_PSYCH_UP": "Psych Up",
    "MOVE_EXTREME_SPEED": "Extreme Speed",
    "MOVE_ANCIENT_POWER": "Ancient Power",
    "MOVE_SHADOW_BALL": "Shadow Ball",
    "MOVE_FUTURE_SIGHT": "Future Sight",
    "MOVE_ROCK_SMASH": "Rock Smash",
    "MOVE_WHIRLPOOL": "Whirlpool",
    "MOVE_BEAT_UP": "Beat Up",
    "MOVE_FAKE_OUT": "Fake Out",
    "MOVE_UPROAR": "Uproar",
    "MOVE_STOCKPILE": "Stockpile",
    "MOVE_SPIT_UP": "Spit Up",
    "MOVE_SWALLOW": "Swallow",
    "MOVE_HEAT_WAVE": "Heat Wave",
    "MOVE_HAIL": "Hail",
    "MOVE_TORMENT": "Torment",
    "MOVE_FLATTER": "Flatter",
    "MOVE_WILL_O_WISP": "Will-O-Wisp",
    "MOVE_MEMENTO": "Memento",
    "MOVE_FACADE": "Facade",
    "MOVE_FOCUS_PUNCH": "Focus Punch",
    "MOVE_SMELLING_SALTS": "Smelling Salts",
    "MOVE_FOLLOW_ME": "Follow Me",
    "MOVE_NATURE_POWER": "Nature Power",
    "MOVE_CHARGE": "Charge",
    "MOVE_TAUNT": "Taunt",
    "MOVE_HELPING_HAND": "Helping Hand",
    "MOVE_TRICK": "Trick",
    "MOVE_ROLE_PLAY": "Role Play",
    "MOVE_WISH": "Wish",
    "MOVE_ASSIST": "Assist",
    "MOVE_INGRAIN": "Ingrain",
    "MOVE_SUPERPOWER": "Superpower",
    "MOVE_MAGIC_COAT": "Magic Coat",
    "MOVE_RECYCLE": "Recycle",
    "MOVE_REVENGE": "Revenge",
    "MOVE_BRICK_BREAK": "Brick Break",
    "MOVE_YAWN": "Yawn",
    "MOVE_KNOCK_OFF": "Knock Off",
    "MOVE_ENDEAVOR": "Endeavor",
    "MOVE_ERUPTION": "Eruption",
    "MOVE_SKILL_SWAP": "Skill Swap",
    "MOVE_IMPRISON": "Imprison",
    "MOVE_REFRESH": "Refresh",
    "MOVE_GRUDGE": "Grudge",
    "MOVE_SNATCH": "Snatch",
    "MOVE_SECRET_POWER": "Secret Power",
    "MOVE_DIVE": "Dive",
    "MOVE_ARM_THRUST": "Arm Thrust",
    "MOVE_CAMOUFLAGE": "Camouflage",
    "MOVE_TAIL_GLOW": "Tail Glow",
    "MOVE_LUSTER_PURGE": "Luster Purge",
    "MOVE_MIST_BALL": "Mist Ball",
    "MOVE_FEATHER_DANCE": "Feather Dance",
    "MOVE_TEETER_DANCE": "Teeter Dance",
    "MOVE_BLAZE_KICK": "Blaze Kick",
    "MOVE_MUD_SPORT": "Mud Sport",
    "MOVE_ICE_BALL": "Ice Ball",
    "MOVE_NEEDLE_ARM": "Needle Arm",
    "MOVE_SLACK_OFF": "Slack Off",
    "MOVE_HYPER_VOICE": "Hyper Voice",
    "MOVE_POISON_FANG": "Poison Fang",
    "MOVE_CRUSH_CLAW": "Crush Claw",
    "MOVE_BLAST_BURN": "Blast Burn",
    "MOVE_HYDRO_CANNON": "Hydro Cannon",
    "MOVE_METEOR_MASH": "Meteor Mash",
    "MOVE_ASTONISH": "Astonish",
    "MOVE_WEATHER_BALL": "Weather Ball",
    "MOVE_AROMATHERAPY": "Aromatherapy",
    "MOVE_FAKE_TEARS": "Fake Tears",
    "MOVE_AIR_CUTTER": "Air Cutter",
    "MOVE_OVERHEAT": "Overheat",
    "MOVE_ODOR_SLEUTH": "Odor Sleuth",
    "MOVE_ROCK_TOMB": "Rock Tomb",
    "MOVE_SILVER_WIND": "Silver Wind",
    "MOVE_METAL_SOUND": "Metal Sound",
    "MOVE_GRASS_WHISTLE": "Grass Whistle",
    "MOVE_TICKLE": "Tickle",
    "MOVE_COSMIC_POWER": "Cosmic Power",
    "MOVE_WATER_SPOUT": "Water Spout",
    "MOVE_SIGNAL_BEAM": "Signal Beam",
    "MOVE_SHADOW_PUNCH": "Shadow Punch",
    "MOVE_EXTRASENSORY": "Extrasensory",
    "MOVE_SKY_UPPERCUT": "Sky Uppercut",
    "MOVE_SAND_TOMB": "Sand Tomb",
    "MOVE_SHEER_COLD": "Sheer Cold",
    "MOVE_MUDDY_WATER": "Muddy Water",
    "MOVE_BULLET_SEED": "Bullet Seed",
    "MOVE_AERIAL_ACE": "Aerial Ace",
    "MOVE_ICICLE_SPEAR": "Icicle Spear",
    "MOVE_IRON_DEFENSE": "Iron Defense",
    "MOVE_BLOCK": "Block",
    "MOVE_HOWL": "Howl",
    "MOVE_DRAGON_CLAW": "Dragon Claw",
    "MOVE_FRENZY_PLANT": "Frenzy Plant",
    "MOVE_BULK_UP": "Bulk Up",
    "MOVE_BOUNCE": "Bounce",
    "MOVE_MUD_SHOT": "Mud Shot",
    "MOVE_POISON_TAIL": "Poison Tail",
    "MOVE_COVET": "Covet",
    "MOVE_VOLT_TACKLE": "Volt Tackle",
    "MOVE_MAGICAL_LEAF": "Magical Leaf",
    "MOVE_WATER_SPORT": "Water Sport",
    "MOVE_CALM_MIND": "Calm Mind",
    "MOVE_LEAF_BLADE": "Leaf Blade",
    "MOVE_DRAGON_DANCE": "Dragon Dance",
    "MOVE_ROCK_BLAST": "Rock Blast",
    "MOVE_SHOCK_WAVE": "Shock Wave",
    "MOVE_WATER_PULSE": "Water Pulse",
    "MOVE_DOOM_DESIRE": "Doom Desire",
    "MOVE_PSYCHO_BOOST": "Psycho Boost",
    "MOVE_ROOST": "Roost",
    "MOVE_GRAVITY": "Gravity",
    "MOVE_MIRACLE_EYE": "Miracle Eye",
    "MOVE_WAKE_UP_SLAP": "Wake Up Slap",
    "MOVE_HAMMER_ARM": "Hammer Arm",
    "MOVE_GYRO_BALL": "Gyro Ball",
    "MOVE_HEALING_WISH": "Healing Wish",
    "MOVE_BRINE": "Brine",
    "MOVE_NATURAL_GIFT": "Natural Gift",
    "MOVE_FEINT": "Feint",
    "MOVE_PLUCK": "Pluck",
    "MOVE_TAILWIND": "Tailwind",
    "MOVE_ACUPRESSURE": "Acupressure",
    "MOVE_METAL_BURST": "Metal Burst",
    "MOVE_U_TURN": "U-turn",
    "MOVE_CLOSE_COMBAT": "Close Combat",
    "MOVE_PAYBACK": "Payback",
    "MOVE_ASSURANCE": "Assurance",
    "MOVE_EMBARGO": "Embargo",
    "MOVE_FLING": "Fling",
    "MOVE_PSYCHO_SHIFT": "Psycho Shift",
    "MOVE_TRUMP_CARD": "Trump Card",
    "MOVE_HEAL_BLOCK": "Heal Block",
    "MOVE_WRING_OUT": "Wring Out",
    "MOVE_POWER_TRICK": "Power Trick",
    "MOVE_GASTRO_ACID": "Gastro Acid",
    "MOVE_LUCKY_CHANT": "Lucky Chant",
    "MOVE_ME_FIRST": "Me First",
    "MOVE_COPYCAT": "Copycat",
    "MOVE_POWER_SWAP": "Power Swap",
    "MOVE_GUARD_SWAP": "Guard Swap",
    "MOVE_PUNISHMENT": "Punishment",
    "MOVE_LAST_RESORT": "Last Resort",
    "MOVE_WORRY_SEED": "Worry Seed",
    "MOVE_SUCKER_PUNCH": "Sucker Punch",
    "MOVE_TOXIC_SPIKES": "Toxic Spikes",
    "MOVE_HEART_SWAP": "Heart Swap",
    "MOVE_AQUA_RING": "Aqua Ring",
    "MOVE_MAGNET_RISE": "Magnet Rise",
    "MOVE_FLARE_BLITZ": "Flare Blitz",
    "MOVE_FORCE_PALM": "Force Palm",
    "MOVE_AURA_SPHERE": "Aura Sphere",
    "MOVE_ROCK_POLISH": "Rock Polish",
    "MOVE_POISON_JAB": "Poison Jab",
    "MOVE_DARK_PULSE": "Dark Pulse",
    "MOVE_NIGHT_SLASH": "Night Slash",
    "MOVE_AQUA_TAIL": "Aqua Tail",
    "MOVE_SEED_BOMB": "Seed Bomb",
    "MOVE_AIR_SLASH": "Air Slash",
    "MOVE_X_SCISSOR": "X-Scissor",
    "MOVE_BUG_BUZZ": "Bug Buzz",
    "MOVE_DRAGON_PULSE": "Dragon Pulse",
    "MOVE_DRAGON_RUSH": "Dragon Rush",
    "MOVE_POWER_GEM": "Power Gem",
    "MOVE_DRAIN_PUNCH": "Drain Punch",
    "MOVE_VACUUM_WAVE": "Vacuum Wave",
    "MOVE_FOCUS_BLAST": "Focus Blast",
    "MOVE_ENERGY_BALL": "Energy Ball",
    "MOVE_BRAVE_BIRD": "Brave Bird",
    "MOVE_EARTH_POWER": "Earth Power",
    "MOVE_SWITCHEROO": "Switcheroo",
    "MOVE_GIGA_IMPACT": "Giga Impact",
    "MOVE_NASTY_PLOT": "Nasty Plot",
    "MOVE_BULLET_PUNCH": "Bullet Punch",
    "MOVE_AVALANCHE": "Avalanche",
    "MOVE_ICE_SHARD": "Ice Shard",
    "MOVE_SHADOW_CLAW": "Shadow Claw",
    "MOVE_THUNDER_FANG": "Thunder Fang",
    "MOVE_ICE_FANG": "Ice Fang",
    "MOVE_FIRE_FANG": "Fire Fang",
    "MOVE_SHADOW_SNEAK": "Shadow Sneak",
    "MOVE_MUD_BOMB": "Mud Bomb",
    "MOVE_PSYCHO_CUT": "Psycho Cut",
    "MOVE_ZEN_HEADBUTT": "Zen Headbutt",
    "MOVE_MIRROR_SHOT": "Mirror Shot",
    "MOVE_FLASH_CANNON": "Flash Cannon",
    "MOVE_ROCK_CLIMB": "Rock Climb",
    "MOVE_DEFOG": "Defog",
    "MOVE_TRICK_ROOM": "Trick Room",
    "MOVE_DRACO_METEOR": "Draco Meteor",
    "MOVE_DISCHARGE": "Discharge",
    "MOVE_LAVA_PLUME": "Lava Plume",
    "MOVE_LEAF_STORM": "Leaf Storm",
    "MOVE_POWER_WHIP": "Power Whip",
    "MOVE_ROCK_WRECKER": "Rock Wrecker",
    "MOVE_CROSS_POISON": "Cross Poison",
    "MOVE_GUNK_SHOT": "Gunk Shot",
    "MOVE_IRON_HEAD": "Iron Head",
    "MOVE_MAGNET_BOMB": "Magnet Bomb",
    "MOVE_STONE_EDGE": "Stone Edge",
    "MOVE_CAPTIVATE": "Captivate",
    "MOVE_STEALTH_ROCK": "Stealth Rock",
    "MOVE_GRASS_KNOT": "Grass Knot",
    "MOVE_CHATTER": "Chatter",
    "MOVE_JUDGMENT": "Judgment",
    "MOVE_BUG_BITE": "Bug Bite",
    "MOVE_CHARGE_BEAM": "Charge Beam",
    "MOVE_WOOD_HAMMER": "Wood Hammer",
    "MOVE_AQUA_JET": "Aqua Jet",
    "MOVE_ATTACK_ORDER": "Attack Order",
    "MOVE_DEFEND_ORDER": "Defend Order",
    "MOVE_HEAL_ORDER": "Heal Order",
    "MOVE_HEAD_SMASH": "Head Smash",
    "MOVE_DOUBLE_HIT": "Double Hit",
    "MOVE_ROAR_OF_TIME": "Roar Of Time",
    "MOVE_SPACIAL_REND": "Spacial Rend",
    "MOVE_LUNAR_DANCE": "Lunar Dance",
    "MOVE_CRUSH_GRIP": "Crush Grip",
    "MOVE_MAGMA_STORM": "Magma Storm",
    "MOVE_DARK_VOID": "Dark Void",
    "MOVE_SEED_FLARE": "Seed Flare",
    "MOVE_OMINOUS_WIND": "Ominous Wind",
    "MOVE_SHADOW_FORCE": "Shadow Force",
    "MOVE_HONE_CLAWS": "Hone Claws",
    "MOVE_WIDE_GUARD": "Wide Guard",
    "MOVE_GUARD_SPLIT": "Guard Split",
    "MOVE_POWER_SPLIT": "Power Split",
    "MOVE_WONDER_ROOM": "Wonder Room",
    "MOVE_PSYSHOCK": "Psyshock",
    "MOVE_VENOSHOCK": "Venoshock",
    "MOVE_AUTOTOMIZE": "Autotomize",
    "MOVE_RAGE_POWDER": "Rage Powder",
    "MOVE_TELEKINESIS": "Telekinesis",
    "MOVE_MAGIC_ROOM": "Magic Room",
    "MOVE_SMACK_DOWN": "Smack Down",
    "MOVE_STORM_THROW": "Storm Throw",
    "MOVE_FLAME_BURST": "Flame Burst",
    "MOVE_SLUDGE_WAVE": "Sludge Wave",
    "MOVE_QUIVER_DANCE": "Quiver Dance",
    "MOVE_HEAVY_SLAM": "Heavy Slam",
    "MOVE_SYNCHRONOISE": "Synchronoise",
    "MOVE_ELECTRO_BALL": "Electro Ball",
    "MOVE_SOAK": "Soak",
    "MOVE_FLAME_CHARGE": "Flame Charge",
    "MOVE_COIL": "Coil",
    "MOVE_LOW_SWEEP": "Low Sweep",
    "MOVE_ACID_SPRAY": "Acid Spray",
    "MOVE_FOUL_PLAY": "Foul Play",
    "MOVE_SIMPLE_BEAM": "Simple Beam",
    "MOVE_ENTRAINMENT": "Entrainment",
    "MOVE_AFTER_YOU": "After You",
    "MOVE_ROUND": "Round",
    "MOVE_ECHOED_VOICE": "Echoed Voice",
    "MOVE_CHIP_AWAY": "Chip Away",
    "MOVE_CLEAR_SMOG": "Clear Smog",
    "MOVE_STORED_POWER": "Stored Power",
    "MOVE_QUICK_GUARD": "Quick Guard",
    "MOVE_ALLY_SWITCH": "Ally Switch",
    "MOVE_SCALD": "Scald",
    "MOVE_SHELL_SMASH": "Shell Smash",
    "MOVE_HEAL_PULSE": "Heal Pulse",
    "MOVE_HEX": "Hex",
    "MOVE_SKY_DROP": "Sky Drop",
    "MOVE_SHIFT_GEAR": "Shift Gear",
    "MOVE_CIRCLE_THROW": "Circle Throw",
    "MOVE_INCINERATE": "Incinerate",
    "MOVE_QUASH": "Quash",
    "MOVE_ACROBATICS": "Acrobatics",
    "MOVE_REFLECT_TYPE": "Reflect Type",
    "MOVE_RETALIATE": "Retaliate",
    "MOVE_FINAL_GAMBIT": "Final Gambit",
    "MOVE_BESTOW": "Bestow",
    "MOVE_INFERNO": "Inferno",
    "MOVE_WATER_PLEDGE": "Water Pledge",
    "MOVE_FIRE_PLEDGE": "Fire Pledge",
    "MOVE_GRASS_PLEDGE": "Grass Pledge",
    "MOVE_VOLT_SWITCH": "Volt Switch",
    "MOVE_STRUGGLE_BUG": "Struggle Bug",
    "MOVE_BULLDOZE": "Bulldoze",
    "MOVE_FROST_BREATH": "Frost Breath",
    "MOVE_DRAGON_TAIL": "Dragon Tail",
    "MOVE_WORK_UP": "Work Up",
    "MOVE_ELECTROWEB": "Electroweb",
    "MOVE_WILD_CHARGE": "Wild Charge",
    "MOVE_DRILL_RUN": "Drill Run",
    "MOVE_DUAL_CHOP": "Dual Chop",
    "MOVE_HEART_STAMP": "Heart Stamp",
    "MOVE_HORN_LEECH": "Horn Leech",
    "MOVE_SACRED_SWORD": "Sacred Sword",
    "MOVE_RAZOR_SHELL": "Razor Shell",
    "MOVE_HEAT_CRASH": "Heat Crash",
    "MOVE_LEAF_TORNADO": "Leaf Tornado",
    "MOVE_STEAMROLLER": "Steamroller",
    "MOVE_COTTON_GUARD": "Cotton Guard",
    "MOVE_NIGHT_DAZE": "Night Daze",
    "MOVE_PSYSTRIKE": "Psystrike",
    "MOVE_TAIL_SLAP": "Tail Slap",
    "MOVE_HURRICANE": "Hurricane",
    "MOVE_HEAD_CHARGE": "Head Charge",
    "MOVE_GEAR_GRIND": "Gear Grind",
    "MOVE_SEARING_SHOT": "Searing Shot",
    "MOVE_TECHNO_BLAST": "Techno Blast",
    "MOVE_RELIC_SONG": "Relic Song",
    "MOVE_SECRET_SWORD": "Secret Sword",
    "MOVE_GLACIATE": "Glaciate",
    "MOVE_BOLT_STRIKE": "Bolt Strike",
    "MOVE_BLUE_FLARE": "Blue Flare",
    "MOVE_FIERY_DANCE": "Fiery Dance",
    "MOVE_FREEZE_SHOCK": "Freeze Shock",
    "MOVE_ICE_BURN": "Ice Burn",
    "MOVE_SNARL": "Snarl",
    "MOVE_ICICLE_CRASH": "Icicle Crash",
    "MOVE_V_CREATE": "V Create",
    "MOVE_FUSION_FLARE": "Fusion Flare",
    "MOVE_FUSION_BOLT": "Fusion Bolt",
    "MOVE_FLYING_PRESS": "Flying Press",
    "MOVE_MAT_BLOCK": "Mat Block",
    "MOVE_BELCH": "Belch",
    "MOVE_ROTOTILLER": "Rototiller",
    "MOVE_STICKY_WEB": "Sticky Web",
    "MOVE_FELL_STINGER": "Fell Stinger",
    "MOVE_PHANTOM_FORCE": "Phantom Force",
    "MOVE_TRICK_OR_TREAT": "Trick Or Treat",
    "MOVE_NOBLE_ROAR": "Noble Roar",
    "MOVE_ION_DELUGE": "Ion Deluge",
    "MOVE_PARABOLIC_CHARGE": "Parabolic Charge",
    "MOVE_FORESTS_CURSE": "Forests Curse",
    "MOVE_PETAL_BLIZZARD": "Petal Blizzard",
    "MOVE_FREEZE_DRY": "Freeze-Dry",
    "MOVE_DISARMING_VOICE": "Disarming Voice",
    "MOVE_PARTING_SHOT": "Parting Shot",
    "MOVE_TOPSY_TURVY": "Topsy Turvy",
    "MOVE_DRAINING_KISS": "Draining Kiss",
    "MOVE_CRAFTY_SHIELD": "Crafty Shield",
    "MOVE_FLOWER_SHIELD": "Flower Shield",
    "MOVE_GRASSY_TERRAIN": "Grassy Terrain",
    "MOVE_MISTY_TERRAIN": "Misty Terrain",
    "MOVE_ELECTRIFY": "Electrify",
    "MOVE_PLAY_ROUGH": "Play Rough",
    "MOVE_FAIRY_WIND": "Fairy Wind",
    "MOVE_MOONBLAST": "Moonblast",
    "MOVE_BOOMBURST": "Boomburst",
    "MOVE_FAIRY_LOCK": "Fairy Lock",
    "MOVE_KINGS_SHIELD": "Kings Shield",
    "MOVE_PLAY_NICE": "Play Nice",
    "MOVE_CONFIDE": "Confide",
    "MOVE_DIAMOND_STORM": "Diamond Storm",
    "MOVE_STEAM_ERUPTION": "Steam Eruption",
    "MOVE_HYPERSPACE_HOLE": "Hyperspace Hole",
    "MOVE_WATER_SHURIKEN": "Water Shuriken",
    "MOVE_MYSTICAL_FIRE": "Mystical Fire",
    "MOVE_SPIKY_SHIELD": "Spiky Shield",
    "MOVE_AROMATIC_MIST": "Aromatic Mist",
    "MOVE_EERIE_IMPULSE": "Eerie Impulse",
    "MOVE_VENOM_DRENCH": "Venom Drench",
    "MOVE_POWDER": "Powder",
    "MOVE_GEOMANCY": "Geomancy",
    "MOVE_MAGNETIC_FLUX": "Magnetic Flux",
    "MOVE_HAPPY_HOUR": "Happy Hour",
    "MOVE_ELECTRIC_TERRAIN": "Electric Terrain",
    "MOVE_DAZZLING_GLEAM": "Dazzling Gleam",
    "MOVE_CELEBRATE": "Celebrate",
    "MOVE_HOLD_HANDS": "Hold Hands",
    "MOVE_BABY_DOLL_EYES": "Baby Doll Eyes",
    "MOVE_NUZZLE": "Nuzzle",
    "MOVE_HOLD_BACK": "Hold Back",
    "MOVE_INFESTATION": "Infestation",
    "MOVE_POWER_UP_PUNCH": "Power Up Punch",
    "MOVE_OBLIVION_WING": "Oblivion Wing",
    "MOVE_THOUSAND_ARROWS": "Thousand Arrows",
    "MOVE_THOUSAND_WAVES": "Thousand Waves",
    "MOVE_LANDS_WRATH": "Lands Wrath",
    "MOVE_LIGHT_OF_RUIN": "Light Of Ruin",
    "MOVE_ORIGIN_PULSE": "Origin Pulse",
    "MOVE_PRECIPICE_BLADES": "Precipice Blades",
    "MOVE_DRAGON_ASCENT": "Dragon Ascent",
    "MOVE_HYPERSPACE_FURY": "Hyperspace Fury",
    "MOVE_SHORE_UP": "Shore Up",
    "MOVE_FIRST_IMPRESSION": "First Impression",
    "MOVE_BANEFUL_BUNKER": "Baneful Bunker",
    "MOVE_SPIRIT_SHACKLE": "Spirit Shackle",
    "MOVE_DARKEST_LARIAT": "Darkest Lariat",
    "MOVE_SPARKLING_ARIA": "Sparkling Aria",
    "MOVE_ICE_HAMMER": "Ice Hammer",
    "MOVE_FLORAL_HEALING": "Floral Healing",
    "MOVE_HIGH_HORSEPOWER": "High Horsepower",
    "MOVE_STRENGTH_SAP": "Strength Sap",
    "MOVE_SOLAR_BLADE": "Solar Blade",
    "MOVE_LEAFAGE": "Leafage",
    "MOVE_SPOTLIGHT": "Spotlight",
    "MOVE_TOXIC_THREAD": "Toxic Thread",
    "MOVE_LASER_FOCUS": "Laser Focus",
    "MOVE_GEAR_UP": "Gear Up",
    "MOVE_THROAT_CHOP": "Throat Chop",
    "MOVE_POLLEN_PUFF": "Pollen Puff",
    "MOVE_ANCHOR_SHOT": "Anchor Shot",
    "MOVE_PSYCHIC_TERRAIN": "Psychic Terrain",
    "MOVE_LUNGE": "Lunge",
    "MOVE_FIRE_LASH": "Fire Lash",
    "MOVE_POWER_TRIP": "Power Trip",
    "MOVE_BURN_UP": "Burn Up",
    "MOVE_SPEED_SWAP": "Speed Swap",
    "MOVE_SMART_STRIKE": "Smart Strike",
    "MOVE_PURIFY": "Purify",
    "MOVE_REVELATION_DANCE": "Revelation Dance",
    "MOVE_CORE_ENFORCER": "Core Enforcer",
    "MOVE_TROP_KICK": "Trop Kick",
    "MOVE_INSTRUCT": "Instruct",
    "MOVE_BEAK_BLAST": "Beak Blast",
    "MOVE_CLANGING_SCALES": "Clanging Scales",
    "MOVE_DRAGON_HAMMER": "Dragon Hammer",
    "MOVE_BRUTAL_SWING": "Brutal Swing",
    "MOVE_AURORA_VEIL": "Aurora Veil",
    "MOVE_SHELL_TRAP": "Shell Trap",
    "MOVE_FLEUR_CANNON": "Fleur Cannon",
    "MOVE_PSYCHIC_FANGS": "Psychic Fangs",
    "MOVE_STOMPING_TANTRUM": "Stomping Tantrum",
    "MOVE_SHADOW_BONE": "Shadow Bone",
    "MOVE_ACCELEROCK": "Accelerock",
    "MOVE_LIQUIDATION": "Liquidation",
    "MOVE_PRISMATIC_LASER": "Prismatic Laser",
    "MOVE_SPECTRAL_THIEF": "Spectral Thief",
    "MOVE_SUNSTEEL_STRIKE": "Sunsteel Strike",
    "MOVE_MOONGEIST_BEAM": "Moongeist Beam",
    "MOVE_TEARFUL_LOOK": "Tearful Look",
    "MOVE_ZING_ZAP": "Zing Zap",
    "MOVE_NATURES_MADNESS": "Natures Madness",
    "MOVE_MULTI_ATTACK": "Multi-Attack",
    "MOVE_MIND_BLOWN": "Mind Blown",
    "MOVE_PLASMA_FISTS": "Plasma Fists",
    "MOVE_PHOTON_GEYSER": "Photon Geyser",
    "MOVE_ZIPPY_ZAP": "Zippy Zap",
    "MOVE_SPLISHY_SPLASH": "Splishy Splash",
    "MOVE_FLOATY_FALL": "Floaty Fall",
    "MOVE_PIKA_PAPOW": "Pika Papow",
    "MOVE_BOUNCY_BUBBLE": "Bouncy Bubble",
    "MOVE_BUZZY_BUZZ": "Buzzy Buzz",
    "MOVE_SIZZLY_SLIDE": "Sizzly Slide",
    "MOVE_GLITZY_GLOW": "Glitzy Glow",
    "MOVE_BADDY_BAD": "Baddy Bad",
    "MOVE_SAPPY_SEED": "Sappy Seed",
    "MOVE_FREEZY_FROST": "Freezy Frost",
    "MOVE_SPARKLY_SWIRL": "Sparkly Swirl",
    "MOVE_VEEVEE_VOLLEY": "Veevee Volley",
    "MOVE_DOUBLE_IRON_BASH": "Double Iron Bash",
    "MOVE_DYNAMAX_CANNON": "Dynamax Cannon",
    "MOVE_SNIPE_SHOT": "Snipe Shot",
    "MOVE_JAW_LOCK": "Jaw Lock",
    "MOVE_STUFF_CHEEKS": "Stuff Cheeks",
    "MOVE_NO_RETREAT": "No Retreat",
    "MOVE_TAR_SHOT": "Tar Shot",
    "MOVE_MAGIC_POWDER": "Magic Powder",
    "MOVE_DRAGON_DARTS": "Dragon Darts",
    "MOVE_TEATIME": "Teatime",
    "MOVE_OCTOLOCK": "Octolock",
    "MOVE_BOLT_BEAK": "Bolt Beak",
    "MOVE_FISHIOUS_REND": "Fishious Rend",
    "MOVE_COURT_CHANGE": "Court Change",
    "MOVE_CLANGOROUS_SOUL": "Clangorous Soul",
    "MOVE_BODY_PRESS": "Body Press",
    "MOVE_DECORATE": "Decorate",
    "MOVE_DRUM_BEATING": "Drum Beating",
    "MOVE_SNAP_TRAP": "Snap Trap",
    "MOVE_PYRO_BALL": "Pyro Ball",
    "MOVE_BEHEMOTH_BLADE": "Behemoth Blade",
    "MOVE_BEHEMOTH_BASH": "Behemoth Bash",
    "MOVE_AURA_WHEEL": "Aura Wheel",
    "MOVE_BREAKING_SWIPE": "Breaking Swipe",
    "MOVE_BRANCH_POKE": "Branch Poke",
    "MOVE_OVERDRIVE": "Overdrive",
    "MOVE_APPLE_ACID": "Apple Acid",
    "MOVE_GRAV_APPLE": "Grav Apple",
    "MOVE_SPIRIT_BREAK": "Spirit Break",
    "MOVE_STRANGE_STEAM": "Strange Steam",
    "MOVE_LIFE_DEW": "Life Dew",
    "MOVE_OBSTRUCT": "Obstruct",
    "MOVE_FALSE_SURRENDER": "False Surrender",
    "MOVE_METEOR_ASSAULT": "Meteor Assault",
    "MOVE_ETERNABEAM": "Eternabeam",
    "MOVE_STEEL_BEAM": "Steel Beam",
    "MOVE_EXPANDING_FORCE": "Expanding Force",
    "MOVE_STEEL_ROLLER": "Steel Roller",
    "MOVE_SCALE_SHOT": "Scale Shot",
    "MOVE_METEOR_BEAM": "Meteor Beam",
    "MOVE_SHELL_SIDE_ARM": "Shell Side Arm",
    "MOVE_MISTY_EXPLOSION": "Misty Explosion",
    "MOVE_GRASSY_GLIDE": "Grassy Glide",
    "MOVE_RISING_VOLTAGE": "Rising Voltage",
    "MOVE_TERRAIN_PULSE": "Terrain Pulse",
    "MOVE_SKITTER_SMACK": "Skitter Smack",
    "MOVE_BURNING_JEALOUSY": "Burning Jealousy",
    "MOVE_LASH_OUT": "Lash Out",
    "MOVE_POLTERGEIST": "Poltergeist",
    "MOVE_CORROSIVE_GAS": "Corrosive Gas",
    "MOVE_COACHING": "Coaching",
    "MOVE_FLIP_TURN": "Flip Turn",
    "MOVE_TRIPLE_AXEL": "Triple Axel",
    "MOVE_DUAL_WINGBEAT": "Dual Wingbeat",
    "MOVE_SCORCHING_SANDS": "Scorching Sands",
    "MOVE_JUNGLE_HEALING": "Jungle Healing",
    "MOVE_WICKED_BLOW": "Wicked Blow",
    "MOVE_SURGING_STRIKES": "Surging Strikes",
    "MOVE_THUNDER_CAGE": "Thunder Cage",
    "MOVE_DRAGON_ENERGY": "Dragon Energy",
    "MOVE_FREEZING_GLARE": "Freezing Glare",
    "MOVE_FIERY_WRATH": "Fiery Wrath",
    "MOVE_THUNDEROUS_KICK": "Thunderous Kick",
    "MOVE_GLACIAL_LANCE": "Glacial Lance",
    "MOVE_ASTRAL_BARRAGE": "Astral Barrage",
    "MOVE_EERIE_SPELL": "Eerie Spell",
    "MOVE_DIRE_CLAW": "Dire Claw",
    "MOVE_PSYSHIELD_BASH": "Psyshield Bash",
    "MOVE_POWER_SHIFT": "Power Shift",
    "MOVE_STONE_AXE": "Stone Axe",
    "MOVE_SPRINGTIDE_STORM": "Springtide Storm",
    "MOVE_MYSTICAL_POWER": "Mystical Power",
    "MOVE_RAGING_FURY": "Raging Fury",
    "MOVE_WAVE_CRASH": "Wave Crash",
    "MOVE_CHLOROBLAST": "Chloroblast",
    "MOVE_MOUNTAIN_GALE": "Mountain Gale",
    "MOVE_VICTORY_DANCE": "Victory Dance",
    "MOVE_HEADLONG_RUSH": "Headlong Rush",
    "MOVE_BARB_BARRAGE": "Barb Barrage",
    "MOVE_ESPER_WING": "Esper Wing",
    "MOVE_BITTER_MALICE": "Bitter Malice",
    "MOVE_SHELTER": "Shelter",
    "MOVE_TRIPLE_ARROWS": "Triple Arrows",
    "MOVE_INFERNAL_PARADE": "Infernal Parade",
    "MOVE_CEASELESS_EDGE": "Ceaseless Edge",
    "MOVE_BLEAKWIND_STORM": "Bleakwind Storm",
    "MOVE_WILDBOLT_STORM": "Wildbolt Storm",
    "MOVE_SANDSEAR_STORM": "Sandsear Storm",
    "MOVE_LUNAR_BLESSING": "Lunar Blessing",
    "MOVE_TAKE_HEART": "Take Heart",
    "MOVE_TERA_BLAST": "Tera Blast",
    "MOVE_SILK_TRAP": "Silk Trap",
    "MOVE_AXE_KICK": "Axe Kick",
    "MOVE_LAST_RESPECTS": "Last Respects",
    "MOVE_LUMINA_CRASH": "Lumina Crash",
    "MOVE_ORDER_UP": "Order Up",
    "MOVE_JET_PUNCH": "Jet Punch",
    "MOVE_SPICY_EXTRACT": "Spicy Extract",
    "MOVE_SPIN_OUT": "Spin Out",
    "MOVE_POPULATION_BOMB": "Population Bomb",
    "MOVE_ICE_SPINNER": "Ice Spinner",
    "MOVE_GLAIVE_RUSH": "Glaive Rush",
    "MOVE_REVIVAL_BLESSING": "Revival Blessing",
    "MOVE_SALT_CURE": "Salt Cure",
    "MOVE_TRIPLE_DIVE": "Triple Dive",
    "MOVE_MORTAL_SPIN": "Mortal Spin",
    "MOVE_DOODLE": "Doodle",
    "MOVE_FILLET_AWAY": "Fillet Away",
    "MOVE_KOWTOW_CLEAVE": "Kowtow Cleave",
    "MOVE_FLOWER_TRICK": "Flower Trick",
    "MOVE_TORCH_SONG": "Torch Song",
    "MOVE_AQUA_STEP": "Aqua Step",
    "MOVE_RAGING_BULL": "Raging Bull",
    "MOVE_MAKE_IT_RAIN": "Make It Rain",
    "MOVE_RUINATION": "Ruination",
    "MOVE_COLLISION_COURSE": "Collision Course",
    "MOVE_ELECTRO_DRIFT": "Electro Drift",
    "MOVE_SHED_TAIL": "Shed Tail",
    "MOVE_CHILLY_RECEPTION": "Chilly Reception",
    "MOVE_TIDY_UP": "Tidy Up",
    "MOVE_SNOWSCAPE": "Snowscape",
    "MOVE_POUNCE": "Pounce",
    "MOVE_TRAILBLAZE": "Trailblaze",
    "MOVE_CHILLING_WATER": "Chilling Water",
    "MOVE_HYPER_DRILL": "Hyper Drill",
    "MOVE_TWIN_BEAM": "Twin Beam",
    "MOVE_RAGE_FIST": "Rage Fist",
    "MOVE_ARMOR_CANNON": "Armor Cannon",
    "MOVE_BITTER_BLADE": "Bitter Blade",
    "MOVE_DOUBLE_SHOCK": "Double Shock",
    "MOVE_GIGATON_HAMMER": "Gigaton Hammer",
    "MOVE_COMEUPPANCE": "Comeuppance",
    "MOVE_AQUA_CUTTER": "Aqua Cutter",
    "MOVE_BLAZING_TORQUE": "Blazing Torque",
    "MOVE_WICKED_TORQUE": "Wicked Torque",
    "MOVE_NOXIOUS_TORQUE": "Noxious Torque",
    "MOVE_COMBAT_TORQUE": "Combat Torque",
    "MOVE_MAGICAL_TORQUE": "Magical Torque",
    "MOVE_PSYBLADE": "Psyblade",
    "MOVE_HYDRO_STEAM": "Hydro Steam",
    "MOVE_BLOOD_MOON": "Blood Moon",
    "MOVE_MATCHA_GOTCHA": "Matcha Gotcha",
    "MOVE_SYRUP_BOMB": "Syrup Bomb",
    "MOVE_IVY_CUDGEL": "Ivy Cudgel",
    "MOVE_ELECTRO_SHOT": "Electro Shot",
    "MOVE_TERA_STARSTORM": "Tera Starstorm",
    "MOVE_FICKLE_BEAM": "Fickle Beam",
    "MOVE_BURNING_BULWARK": "Burning Bulwark",
    "MOVE_THUNDERCLAP": "Thunderclap",
    "MOVE_MIGHTY_CLEAVE": "Mighty Cleave",
    "MOVE_TACHYON_CUTTER": "Tachyon Cutter",
    "MOVE_HARD_PRESS": "Hard Press",
    "MOVE_DRAGON_CHEER": "Dragon Cheer",
    "MOVE_ALLURING_VOICE": "Alluring Voice",
    "MOVE_TEMPER_FLARE": "Temper Flare",
    "MOVE_SUPERCELL_SLAM": "Supercell Slam",
    "MOVE_PSYCHIC_NOISE": "Psychic Noise",
    "MOVE_UPPER_HAND": "Upper Hand",
    "MOVE_MALIGNANT_CHAIN": "Malignant Chain",
}