nature_names = {
    "NATURE_HARDY": "Hardy",
    "NATURE_LONELY": "Lonely",
    "NATURE_BRAVE": "Brave",
    "NATURE_ADAMANT": "Adamant",
    "NATURE_NAUGHTY": "Naughty",
    "NATURE_BOLD": "Bold",
    "NATURE_DOCILE": "Docile",
    "NATURE_RELAXED": "Relaxed",
    "NATURE_IMPISH": "Impish",
    "NATURE_LAX": "Lax",
    "NATURE_TIMID": "Timid",
    "NATURE_HASTY": "Hasty",
    "NATURE_SERIOUS": "Serious",
    "NATURE_JOLLY": "Jolly",
    "NATURE_NAIVE": "Naive",
    "NATURE_MODEST": "Modest",
    "NATURE_MILD": "Mild",
    "NATURE_QUIET": "Quiet",
    "NATURE_BASHFUL": "Bashful",
    "NATURE_RASH": "Rash",
    "NATURE_CALM": "Calm",
    "NATURE_GENTLE": "Gentle",
    "NATURE_SASSY": "Sassy",
    "NATURE_CAREFUL": "Careful",
    "NATURE_QUIRKY": "Quirky",
}

status_names = {
    "STATUS1_NONE": "None",
    "STATUS1_SLEEP": "Sleep",
    "STATUS1_POISON": "Poison",
    "STATUS1_BURN": "Burn",
    "STATUS1_FREEZE": "Freeze",
    "STATUS1_PARALYSIS": "Paralysis",
    "STATUS1_TOXIC_POISON": "Toxic Poison",
}

tera_types = {
    "TYPE_NORMAL": "Tera Normal",
    "TYPE_FIGHTING": "Tera Fighting",
    "TYPE_FLYING": "Tera Flying",
    "TYPE_POISON": "Tera Poison",
    "TYPE_GROUND": "Tera Ground",
    "TYPE_ROCK": "Tera Rock",
    "TYPE_BUG": "Tera Bug",
    "TYPE_GHOST": "Tera Ghost",
    "TYPE_STEEL": "Tera Steel",
    "TYPE_FIRE": "Tera Fire",
    "TYPE_WATER": "Tera Water",
    "TYPE_GRASS": "Tera Grass",
    "TYPE_ELECTRIC": "Tera Electric",
    "TYPE_PSYCHIC": "Tera Psychic",
    "TYPE_ICE": "Tera Ice",
    "TYPE_DRAGON": "Tera Dragon",
    "TYPE_DARK": "Tera Dark",
    "TYPE_FAIRY": "Tera Fairy",
    "TYPE_STELLAR": "Tera Stellar",
}